package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmsProductPlan<M extends BasePmsProductPlan<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 方案名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 方案名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 设备型号 id（方案适配的设备型号）
	 */
	public void setDevModeId(java.lang.Integer devModeId) {
		set("dev_mode_id", devModeId);
	}
	
	/**
	 * 设备型号 id（方案适配的设备型号）
	 */
	public java.lang.Integer getDevModeId() {
		return getInt("dev_mode_id");
	}

	/**
	 * 设备型号 name
	 */
	public void setDevMode(java.lang.String devMode) {
		set("dev_mode", devMode);
	}
	
	/**
	 * 设备型号 name
	 */
	public java.lang.String getDevMode() {
		return getStr("dev_mode");
	}

	/**
	 * 设备格子  - 商品 - 价格
	 */
	public void setPlan(java.lang.String plan) {
		set("plan", plan);
	}
	
	/**
	 * 设备格子  - 商品 - 价格
	 */
	public java.lang.String getPlan() {
		return getStr("plan");
	}

}
