package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsDeviceQrcodeRecord<M extends BaseDmsDeviceQrcodeRecord<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 设备Id
	 */
	public void setDeviceId(java.math.BigInteger deviceId) {
		set("device_id", deviceId);
	}
	
	/**
	 * 设备Id
	 */
	public java.math.BigInteger getDeviceId() {
		return get("device_id");
	}

	/**
	 * 设备编号
	 */
	public void setDeviceSn(java.lang.String deviceSn) {
		set("device_sn", deviceSn);
	}
	
	/**
	 * 设备编号
	 */
	public java.lang.String getDeviceSn() {
		return getStr("device_sn");
	}

	/**
	 * 场所Id
	 */
	public void setPlaceId(java.lang.Long placeId) {
		set("place_id", placeId);
	}
	
	/**
	 * 场所Id
	 */
	public java.lang.Long getPlaceId() {
		return getLong("place_id");
	}

	/**
	 * 场所名称
	 */
	public void setPlaceName(java.lang.String placeName) {
		set("place_name", placeName);
	}
	
	/**
	 * 场所名称
	 */
	public java.lang.String getPlaceName() {
		return getStr("place_name");
	}

	/**
	 * 房间号
	 */
	public void setRoomNo(java.lang.String roomNo) {
		set("room_no", roomNo);
	}
	
	/**
	 * 房间号
	 */
	public java.lang.String getRoomNo() {
		return getStr("room_no");
	}

	/**
	 * 扫码时间
	 */
	public void setScannedTime(java.util.Date scannedTime) {
		set("scanned_time", scannedTime);
	}
	
	/**
	 * 扫码时间
	 */
	public java.util.Date getScannedTime() {
		return get("scanned_time");
	}

	/**
	 * 扫码设备的Ip地址
	 */
	public void setScannedIp(java.lang.String scannedIp) {
		set("scanned_ip", scannedIp);
	}
	
	/**
	 * 扫码设备的Ip地址
	 */
	public java.lang.String getScannedIp() {
		return getStr("scanned_ip");
	}

	/**
	 * 合伙人Id
	 */
	public void setPartnerBy(java.lang.Long partnerBy) {
		set("partner_by", partnerBy);
	}
	
	/**
	 * 合伙人Id
	 */
	public java.lang.Long getPartnerBy() {
		return getLong("partner_by");
	}

}
