package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanProductAdmin<M extends BasePlanProductAdmin<M>> extends Model<M> implements IBean {

	/**
	 * 商品方案与用户的关系表，主键Id
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 商品方案与用户的关系表，主键Id
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 商品方案的Id
	 */
	public void setPlanId(java.math.BigInteger planId) {
		set("plan_id", planId);
	}
	
	/**
	 * 商品方案的Id
	 */
	public java.math.BigInteger getPlanId() {
		return get("plan_id");
	}

	/**
	 * 用户Id
	 */
	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 用户Id
	 */
	public java.lang.Integer getAdminId() {
		return getInt("admin_id");
	}

	/**
	 * 绑定关系枚举类BindType：酒店与人员的绑定关系：2-推广关系、3-酒店管理（场所）、4-酒店补货
	 */
	public void setBindType(java.lang.Integer bindType) {
		set("bind_type", bindType);
	}
	
	/**
	 * 绑定关系枚举类BindType：酒店与人员的绑定关系：2-推广关系、3-酒店管理（场所）、4-酒店补货
	 */
	public java.lang.Integer getBindType() {
		return getInt("bind_type");
	}

	/**
	 * 是否启用该关系（0-false-不启用、1-true-启用）
	 */
	public void setIsEnable(java.lang.Boolean isEnable) {
		set("is_enable", isEnable);
	}
	
	/**
	 * 是否启用该关系（0-false-不启用、1-true-启用）
	 */
	public java.lang.Boolean getIsEnable() {
		return get("is_enable");
	}

	/**
	 * 备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
