package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsRedPlan<M extends BaseDdmsRedPlan<M>> extends Model<M> implements IBean {

	/**
	 * 红包方案Id
	 */
	public void setRedId(java.lang.Long redId) {
		set("red_id", redId);
	}
	
	/**
	 * 红包方案Id
	 */
	public java.lang.Long getRedId() {
		return getLong("red_id");
	}

	/**
	 * 方案名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 方案名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 红包概率类型（1-随机，2-自定义）
	 */
	public void setProbabilityType(java.lang.Long probabilityType) {
		set("probability_type", probabilityType);
	}
	
	/**
	 * 红包概率类型（1-随机，2-自定义）
	 */
	public java.lang.Long getProbabilityType() {
		return getLong("probability_type");
	}

	/**
	 * 红包有效时间（单位：小时），产生订单后，多少小时内补货可以领取红包
	 */
	public void setEffectiveTime(java.lang.Long effectiveTime) {
		set("effective_time", effectiveTime);
	}
	
	/**
	 * 红包有效时间（单位：小时），产生订单后，多少小时内补货可以领取红包
	 */
	public java.lang.Long getEffectiveTime() {
		return getLong("effective_time");
	}

	/**
	 * 是否为默认策略（如设置为：是，新增场所会自动绑定该红包策略）
	 */
	public void setIsDefault(java.lang.Boolean isDefault) {
		set("is_default", isDefault);
	}
	
	/**
	 * 是否为默认策略（如设置为：是，新增场所会自动绑定该红包策略）
	 */
	public java.lang.Boolean getIsDefault() {
		return get("is_default");
	}

	/**
	 * 到账方式（1-系统钱包，2-微信钱包）
	 */
	public void setAccountType(java.lang.Long accountType) {
		set("account_type", accountType);
	}
	
	/**
	 * 到账方式（1-系统钱包，2-微信钱包）
	 */
	public java.lang.Long getAccountType() {
		return getLong("account_type");
	}

	/**
	 * 红包最小值（最小值为：0.3）
	 */
	public void setRedMin(java.math.BigDecimal redMin) {
		set("red_min", redMin);
	}
	
	/**
	 * 红包最小值（最小值为：0.3）
	 */
	public java.math.BigDecimal getRedMin() {
		return get("red_min");
	}

	/**
	 * 红包最大值（建议最大值为：10）
	 */
	public void setRedMax(java.math.BigDecimal redMax) {
		set("red_max", redMax);
	}
	
	/**
	 * 红包最大值（建议最大值为：10）
	 */
	public java.math.BigDecimal getRedMax() {
		return get("red_max");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
