package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderTest<M extends BaseOrderTest<M>> extends Model<M> implements IBean {

	/**
	 * 导出的订单表格id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 导出的订单表格id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 订单编号
	 */
	public void setOrderNumber(java.lang.String orderNumber) {
		set("order_number", orderNumber);
	}
	
	/**
	 * 订单编号
	 */
	public java.lang.String getOrderNumber() {
		return getStr("order_number");
	}

	/**
	 * 设备ID
	 */
	public void setDevId(java.lang.String devId) {
		set("dev_id", devId);
	}
	
	/**
	 * 设备ID
	 */
	public java.lang.String getDevId() {
		return getStr("dev_id");
	}

	/**
	 * 运维管理人员
	 */
	public void setMaintenanceUser(java.lang.String maintenanceUser) {
		set("maintenance_user", maintenanceUser);
	}
	
	/**
	 * 运维管理人员
	 */
	public java.lang.String getMaintenanceUser() {
		return getStr("maintenance_user");
	}

	/**
	 * 合伙人名称
	 */
	public void setPartnerUser(java.lang.String partnerUser) {
		set("partner_user", partnerUser);
	}
	
	/**
	 * 合伙人名称
	 */
	public java.lang.String getPartnerUser() {
		return getStr("partner_user");
	}

	/**
	 * 场所名称
	 */
	public void setPlaceName(java.lang.String placeName) {
		set("place_name", placeName);
	}
	
	/**
	 * 场所名称
	 */
	public java.lang.String getPlaceName() {
		return getStr("place_name");
	}

	/**
	 * 房间号
	 */
	public void setRoomNumber(java.lang.String roomNumber) {
		set("room_number", roomNumber);
	}
	
	/**
	 * 房间号
	 */
	public java.lang.String getRoomNumber() {
		return getStr("room_number");
	}

	/**
	 * 应付的金额
	 */
	public void setActualPayment(java.lang.String actualPayment) {
		set("actual_payment", actualPayment);
	}
	
	/**
	 * 应付的金额
	 */
	public java.lang.String getActualPayment() {
		return getStr("actual_payment");
	}

	/**
	 * 优惠金额
	 */
	public void setCoupon(java.lang.String coupon) {
		set("coupon", coupon);
	}
	
	/**
	 * 优惠金额
	 */
	public java.lang.String getCoupon() {
		return getStr("coupon");
	}

	/**
	 * 优惠的描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 优惠的描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 实际的金额
	 */
	public void setActualPayments(java.lang.String actualPayments) {
		set("actual_payments", actualPayments);
	}
	
	/**
	 * 实际的金额
	 */
	public java.lang.String getActualPayments() {
		return getStr("actual_payments");
	}

	/**
	 * 支付的类型
	 */
	public void setPayType(java.lang.String payType) {
		set("pay_type", payType);
	}
	
	/**
	 * 支付的类型
	 */
	public java.lang.String getPayType() {
		return getStr("pay_type");
	}

	/**
	 * 订单的状态
	 */
	public void setOrderType(java.lang.String orderType) {
		set("order_type", orderType);
	}
	
	/**
	 * 订单的状态
	 */
	public java.lang.String getOrderType() {
		return getStr("order_type");
	}

	/**
	 * 交易单号
	 */
	public void setNumbers(java.lang.String numbers) {
		set("numbers", numbers);
	}
	
	/**
	 * 交易单号
	 */
	public java.lang.String getNumbers() {
		return getStr("numbers");
	}

	/**
	 * 付款时间
	 */
	public void setTimePayment(java.util.Date timePayment) {
		set("time_payment", timePayment);
	}
	
	/**
	 * 付款时间
	 */
	public java.util.Date getTimePayment() {
		return get("time_payment");
	}

	/**
	 * 下单时间
	 */
	public void setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
	}
	
	/**
	 * 下单时间
	 */
	public java.util.Date getOrderTime() {
		return get("order_time");
	}

	/**
	 * 商品名称
	 */
	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	/**
	 * 柜子号
	 */
	public void setContainerNumber(java.lang.Integer containerNumber) {
		set("container_number", containerNumber);
	}
	
	/**
	 * 柜子号
	 */
	public java.lang.Integer getContainerNumber() {
		return getInt("container_number");
	}

	/**
	 * 商品单价
	 */
	public void setCommodityPrice(java.lang.String commodityPrice) {
		set("commodity_price", commodityPrice);
	}
	
	/**
	 * 商品单价
	 */
	public java.lang.String getCommodityPrice() {
		return getStr("commodity_price");
	}

	/**
	 * 购买的数量
	 */
	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 购买的数量
	 */
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	/**
	 * 商品小计的价格
	 */
	public void setPrice(java.lang.String price) {
		set("price", price);
	}
	
	/**
	 * 商品小计的价格
	 */
	public java.lang.String getPrice() {
		return getStr("price");
	}

	/**
	 * db
	 */
	public void setUserBd(java.lang.String userBd) {
		set("user_bd", userBd);
	}
	
	/**
	 * db
	 */
	public java.lang.String getUserBd() {
		return getStr("user_bd");
	}

}
