package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUmsProblemFeedback<M extends BaseUmsProblemFeedback<M>> extends Model<M> implements IBean {

	/**
	 * 问题反馈表
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 问题反馈表
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 第一张图片
	 */
	public void setUrlImg(java.lang.String urlImg) {
		set("url_img", urlImg);
	}
	
	/**
	 * 第一张图片
	 */
	public java.lang.String getUrlImg() {
		return getStr("url_img");
	}

	/**
	 * 第二张图片
	 */
	public void setUrlImgTwo(java.lang.String urlImgTwo) {
		set("url_img_two", urlImgTwo);
	}
	
	/**
	 * 第二张图片
	 */
	public java.lang.String getUrlImgTwo() {
		return getStr("url_img_two");
	}

	/**
	 * 第三张图片
	 */
	public void setUrlImgThree(java.lang.String urlImgThree) {
		set("url_img_three", urlImgThree);
	}
	
	/**
	 * 第三张图片
	 */
	public java.lang.String getUrlImgThree() {
		return getStr("url_img_three");
	}

	/**
	 * 创建的时间
	 */
	public void setCreationTime(java.util.Date creationTime) {
		set("creation_time", creationTime);
	}
	
	/**
	 * 创建的时间
	 */
	public java.util.Date getCreationTime() {
		return get("creation_time");
	}

	/**
	 * 用户的ID
	 */
	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 用户的ID
	 */
	public java.lang.Integer getAdminId() {
		return getInt("admin_id");
	}

	/**
	 * 用户的名称
	 */
	public void setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
	}
	
	/**
	 * 用户的名称
	 */
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	/**
	 * 1-改善建议类2-新需求类3-系统BUG类
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 1-改善建议类2-新需求类3-系统BUG类
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
