package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsWithdrawConf<M extends BaseDdmsWithdrawConf<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 开始金额
	 */
	public void setBeginAmount(java.math.BigDecimal beginAmount) {
		set("begin_amount", beginAmount);
	}
	
	/**
	 * 开始金额
	 */
	public java.math.BigDecimal getBeginAmount() {
		return get("begin_amount");
	}

	/**
	 * 结束金额
	 */
	public void setEndAmount(java.math.BigDecimal endAmount) {
		set("end_amount", endAmount);
	}
	
	/**
	 * 结束金额
	 */
	public java.math.BigDecimal getEndAmount() {
		return get("end_amount");
	}

	/**
	 * 计算模型(0-百分比、1-固定金额)
	 */
	public void setCalModel(java.lang.Integer calModel) {
		set("cal_model", calModel);
	}
	
	/**
	 * 计算模型(0-百分比、1-固定金额)
	 */
	public java.lang.Integer getCalModel() {
		return getInt("cal_model");
	}

	/**
	 * 提现值（手续费值）
	 */
	public void setDisWithdrawValue(java.lang.String disWithdrawValue) {
		set("dis_withdraw_value", disWithdrawValue);
	}
	
	/**
	 * 提现值（手续费值）
	 */
	public java.lang.String getDisWithdrawValue() {
		return getStr("dis_withdraw_value");
	}

	/**
	 * 是否删除(0-false-已删除、1-true-未删除)
	 */
	public void setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除(0-false-已删除、1-true-未删除)
	 */
	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	/**
	 * 添加时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 添加时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
