package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsWithdrawRecord<M extends BaseDdmsWithdrawRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户id
	 */
	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	/**
	 * 提现单号
	 */
	public void setWithdrawNum(java.lang.String withdrawNum) {
		set("withdraw_num", withdrawNum);
	}
	
	/**
	 * 提现单号
	 */
	public java.lang.String getWithdrawNum() {
		return getStr("withdraw_num");
	}

	/**
	 * 提现金额
	 */
	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
	}
	
	/**
	 * 提现金额
	 */
	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	/**
	 * 手续费
	 */
	public void setServiceAmount(java.math.BigDecimal serviceAmount) {
		set("service_amount", serviceAmount);
	}
	
	/**
	 * 手续费
	 */
	public java.math.BigDecimal getServiceAmount() {
		return get("service_amount");
	}

	/**
	 * 实际到账金额
	 */
	public void setRealAmount(java.math.BigDecimal realAmount) {
		set("real_amount", realAmount);
	}
	
	/**
	 * 实际到账金额
	 */
	public java.math.BigDecimal getRealAmount() {
		return get("real_amount");
	}

	/**
	 * 提现时间
	 */
	public void setWithdrawTime(java.util.Date withdrawTime) {
		set("withdraw_time", withdrawTime);
	}
	
	/**
	 * 提现时间
	 */
	public java.util.Date getWithdrawTime() {
		return get("withdraw_time");
	}

	/**
	 * 处理时间
	 */
	public void setHandleTime(java.util.Date handleTime) {
		set("handle_time", handleTime);
	}
	
	/**
	 * 处理时间
	 */
	public java.util.Date getHandleTime() {
		return get("handle_time");
	}

	/**
	 * 处理状态,1-申请中，2-已经发放3-不允许发放
	 */
	public void setWithdrawStatus(java.lang.Integer withdrawStatus) {
		set("withdraw_status", withdrawStatus);
	}
	
	/**
	 * 处理状态,1-申请中，2-已经发放3-不允许发放
	 */
	public java.lang.Integer getWithdrawStatus() {
		return getInt("withdraw_status");
	}

	/**
	 * 提现账户
	 */
	public void setAccountType(java.lang.String accountType) {
		set("account_type", accountType);
	}
	
	/**
	 * 提现账户
	 */
	public java.lang.String getAccountType() {
		return getStr("account_type");
	}

}
