package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsDeviceProductPlan<M extends BaseDmsDeviceProductPlan<M>> extends Model<M> implements IBean {

	/**
	 * 设备与商品方案的关系表Id
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 设备与商品方案的关系表Id
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 设备 Id
	 */
	public void setDeviceId(java.lang.Long deviceId) {
		set("device_id", deviceId);
	}
	
	/**
	 * 设备 Id
	 */
	public java.lang.Long getDeviceId() {
		return getLong("device_id");
	}

	/**
	 * 商品方案 Id
	 */
	public void setPlanId(java.math.BigInteger planId) {
		set("plan_id", planId);
	}
	
	/**
	 * 商品方案 Id
	 */
	public java.math.BigInteger getPlanId() {
		return get("plan_id");
	}

	/**
	 * 绑定时间
	 */
	public void setBindTime(java.util.Date bindTime) {
		set("bind_time", bindTime);
	}
	
	/**
	 * 绑定时间
	 */
	public java.util.Date getBindTime() {
		return get("bind_time");
	}

	/**
	 * 是否删除（1-未删除，0-已删除）
	 */
	public void setStatusDel(java.lang.Integer statusDel) {
		set("status_del", statusDel);
	}
	
	/**
	 * 是否删除（1-未删除，0-已删除）
	 */
	public java.lang.Integer getStatusDel() {
		return getInt("status_del");
	}

}
