package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsAdminAmount<M extends BaseDdmsAdminAmount<M>> extends Model<M> implements IBean {

	/**
	 * 账户钱包金额表Id
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 账户钱包金额表Id
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 用户表id
	 */
	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 用户表id
	 */
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	/**
	 * 用户名称
	 */
	public void setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
	}
	
	/**
	 * 用户名称
	 */
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	/**
	 * 总金额
	 */
	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
	}
	
	/**
	 * 总金额
	 */
	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	/**
	 * 冻结金额
	 */
	public void setFrozenAmount(java.math.BigDecimal frozenAmount) {
		set("frozen_amount", frozenAmount);
	}
	
	/**
	 * 冻结金额
	 */
	public java.math.BigDecimal getFrozenAmount() {
		return get("frozen_amount");
	}

	/**
	 * 可用金额
	 */
	public void setAvaibleAmount(java.math.BigDecimal avaibleAmount) {
		set("avaible_amount", avaibleAmount);
	}
	
	/**
	 * 可用金额
	 */
	public java.math.BigDecimal getAvaibleAmount() {
		return get("avaible_amount");
	}

	/**
	 * 本次欠款
	 */
	public void setCurrentDebtAmount(java.math.BigDecimal currentDebtAmount) {
		set("current_debt_amount", currentDebtAmount);
	}
	
	/**
	 * 本次欠款
	 */
	public java.math.BigDecimal getCurrentDebtAmount() {
		return get("current_debt_amount");
	}

	/**
	 * 总欠款
	 */
	public void setTotalDebtAmount(java.math.BigDecimal totalDebtAmount) {
		set("total_debt_amount", totalDebtAmount);
	}
	
	/**
	 * 总欠款
	 */
	public java.math.BigDecimal getTotalDebtAmount() {
		return get("total_debt_amount");
	}

	/**
	 * 类型（0会员 1 代理商）
	 */
	public void setIdentityType(java.lang.Integer identityType) {
		set("identity_type", identityType);
	}
	
	/**
	 * 类型（0会员 1 代理商）
	 */
	public java.lang.Integer getIdentityType() {
		return getInt("identity_type");
	}

	/**
	 * 状态（0正常 1冻结）
	 */
	public void setAmountStatus(java.lang.Integer amountStatus) {
		set("amount_status", amountStatus);
	}
	
	/**
	 * 状态（0正常 1冻结）
	 */
	public java.lang.Integer getAmountStatus() {
		return getInt("amount_status");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 扩展字段，交易账户总金额
	 */
	public void setTradeTotalAmount(java.math.BigDecimal tradeTotalAmount) {
		set("trade_total_amount", tradeTotalAmount);
	}
	
	/**
	 * 扩展字段，交易账户总金额
	 */
	public java.math.BigDecimal getTradeTotalAmount() {
		return get("trade_total_amount");
	}

	/**
	 * 扩展字段，交易账户冻结金额
	 */
	public void setTradeFrozenAmount(java.math.BigDecimal tradeFrozenAmount) {
		set("trade_frozen_amount", tradeFrozenAmount);
	}
	
	/**
	 * 扩展字段，交易账户冻结金额
	 */
	public java.math.BigDecimal getTradeFrozenAmount() {
		return get("trade_frozen_amount");
	}

	/**
	 * 扩展字段，交易账户可用金额
	 */
	public void setTradeAvaibleAmount(java.math.BigDecimal tradeAvaibleAmount) {
		set("trade_avaible_amount", tradeAvaibleAmount);
	}
	
	/**
	 * 扩展字段，交易账户可用金额
	 */
	public java.math.BigDecimal getTradeAvaibleAmount() {
		return get("trade_avaible_amount");
	}

	/**
	 * 扩展字段，等级账户总金额
	 */
	public void setLevelTotalAmount(java.math.BigDecimal levelTotalAmount) {
		set("level_total_amount", levelTotalAmount);
	}
	
	/**
	 * 扩展字段，等级账户总金额
	 */
	public java.math.BigDecimal getLevelTotalAmount() {
		return get("level_total_amount");
	}

	/**
	 * 扩展字段，等级账户冻结金额
	 */
	public void setLevelFrozenAmount(java.math.BigDecimal levelFrozenAmount) {
		set("level_frozen_amount", levelFrozenAmount);
	}
	
	/**
	 * 扩展字段，等级账户冻结金额
	 */
	public java.math.BigDecimal getLevelFrozenAmount() {
		return get("level_frozen_amount");
	}

	/**
	 * 扩展字段，等级账户可用金额
	 */
	public void setLevelAvaibleAmount(java.math.BigDecimal levelAvaibleAmount) {
		set("level_avaible_amount", levelAvaibleAmount);
	}
	
	/**
	 * 扩展字段，等级账户可用金额
	 */
	public java.math.BigDecimal getLevelAvaibleAmount() {
		return get("level_avaible_amount");
	}

	/**
	 * 扩展字段，邀请用户总积分
	 */
	public void setInviteTotalAmount(java.math.BigDecimal inviteTotalAmount) {
		set("invite_total_amount", inviteTotalAmount);
	}
	
	/**
	 * 扩展字段，邀请用户总积分
	 */
	public java.math.BigDecimal getInviteTotalAmount() {
		return get("invite_total_amount");
	}

	/**
	 * 扩展字段，邀请用户冻结积分
	 */
	public void setInviteFrozenAmount(java.math.BigDecimal inviteFrozenAmount) {
		set("invite_frozen_amount", inviteFrozenAmount);
	}
	
	/**
	 * 扩展字段，邀请用户冻结积分
	 */
	public java.math.BigDecimal getInviteFrozenAmount() {
		return get("invite_frozen_amount");
	}

	/**
	 * 扩展字段，邀请用户可用积分
	 */
	public void setInviteAvaibleAmount(java.math.BigDecimal inviteAvaibleAmount) {
		set("invite_avaible_amount", inviteAvaibleAmount);
	}
	
	/**
	 * 扩展字段，邀请用户可用积分
	 */
	public java.math.BigDecimal getInviteAvaibleAmount() {
		return get("invite_avaible_amount");
	}

}
