package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsDevice<M extends BaseDmsDevice<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 设备编号
	 */
	public void setDeviceSn(java.lang.String deviceSn) {
		set("device_sn", deviceSn);
	}
	
	/**
	 * 设备编号
	 */
	public java.lang.String getDeviceSn() {
		return getStr("device_sn");
	}

	/**
	 * MAC地址
	 */
	public void setDeviceMac(java.lang.String deviceMac) {
		set("device_mac", deviceMac);
	}
	
	/**
	 * MAC地址
	 */
	public java.lang.String getDeviceMac() {
		return getStr("device_mac");
	}

	/**
	 * 设备型号（每一种型号，具有不同的设备格子）
	 */
	public void setDeviceMode(java.lang.String deviceMode) {
		set("device_mode", deviceMode);
	}
	
	/**
	 * 设备型号（每一种型号，具有不同的设备格子）
	 */
	public java.lang.String getDeviceMode() {
		return getStr("device_mode");
	}

	/**
	 * 蓝牙Id
	 */
	public void setBlueId(java.lang.String blueId) {
		set("blue_id", blueId);
	}
	
	/**
	 * 蓝牙Id
	 */
	public java.lang.String getBlueId() {
		return getStr("blue_id");
	}

	/**
	 * 设备二维码
	 */
	public void setDeviceQr(java.lang.String deviceQr) {
		set("device_qr", deviceQr);
	}
	
	/**
	 * 设备二维码
	 */
	public java.lang.String getDeviceQr() {
		return getStr("device_qr");
	}

	/**
	 * 协议类型
	 */
	public void setProtocol(java.lang.Integer protocol) {
		set("protocol", protocol);
	}
	
	/**
	 * 协议类型
	 */
	public java.lang.Integer getProtocol() {
		return getInt("protocol");
	}

	/**
	 * 电池电量
	 */
	public void setPower(java.lang.String power) {
		set("power", power);
	}
	
	/**
	 * 电池电量
	 */
	public java.lang.String getPower() {
		return getStr("power");
	}

	/**
	 * 供电类型
	 */
	public void setPowerType(java.lang.Integer powerType) {
		set("power_type", powerType);
	}
	
	/**
	 * 供电类型
	 */
	public java.lang.Integer getPowerType() {
		return getInt("power_type");
	}

	/**
	 * 设备激活时间
	 */
	public void setActivateTime(java.util.Date activateTime) {
		set("activate_time", activateTime);
	}
	
	/**
	 * 设备激活时间
	 */
	public java.util.Date getActivateTime() {
		return get("activate_time");
	}

	/**
	 * 设备入库时间
	 */
	public void setEntryTime(java.util.Date entryTime) {
		set("entry_time", entryTime);
	}
	
	/**
	 * 设备入库时间
	 */
	public java.util.Date getEntryTime() {
		return get("entry_time");
	}

	/**
	 * 备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
