package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUmsAdminPermissionRelation<M extends BaseUmsAdminPermissionRelation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	public void setPermissionId(java.lang.Long permissionId) {
		set("permission_id", permissionId);
	}
	
	public java.lang.Long getPermissionId() {
		return getLong("permission_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
