package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsDistributionPlan<M extends BaseDdmsDistributionPlan<M>> extends Model<M> implements IBean {

	/**
	 * 场所分成表的Id（分成方案）
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 场所分成表的Id（分成方案）
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 方案名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 方案名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 分成类型，枚举类DivideModeType（1-营业额，2-利润，3-商品的分成）
	 */
	public void setDivideMode(java.lang.Long divideMode) {
		set("divide_mode", divideMode);
	}
	
	/**
	 * 分成类型，枚举类DivideModeType（1-营业额，2-利润，3-商品的分成）
	 */
	public java.lang.Long getDivideMode() {
		return getLong("divide_mode");
	}

	/**
	 * 设备类型（1-普通售货机；2-充电线）
	 */
	public void setDeviceType(java.lang.Long deviceType) {
		set("device_type", deviceType);
	}
	
	/**
	 * 设备类型（1-普通售货机；2-充电线）
	 */
	public java.lang.Long getDeviceType() {
		return getLong("device_type");
	}

	/**
	 * 当前可分配的总分成
	 */
	public void setAvaibleDevice(java.math.BigDecimal avaibleDevice) {
		set("avaible_device", avaibleDevice);
	}
	
	/**
	 * 当前可分配的总分成
	 */
	public java.math.BigDecimal getAvaibleDevice() {
		return get("avaible_device");
	}

	/**
	 * 分成模式：0-普通分成模式、1-动态分成模式
	 */
	public void setShareMode(java.lang.Long shareMode) {
		set("share_mode", shareMode);
	}
	
	/**
	 * 分成模式：0-普通分成模式、1-动态分成模式
	 */
	public java.lang.Long getShareMode() {
		return getLong("share_mode");
	}

	/**
	 * 分成比例详情，json格式（user : 分成用户Id,  ratio:分成比例 : x% 手续费：service_rate）
	 */
	public void setDetails(java.lang.String details) {
		set("details", details);
	}
	
	/**
	 * 分成比例详情，json格式（user : 分成用户Id,  ratio:分成比例 : x% 手续费：service_rate）
	 */
	public java.lang.String getDetails() {
		return getStr("details");
	}

	/**
	 * 状态（0-删除 未启用，1-未删除 已经启用）
	 */
	public void setStatusDel(java.lang.Integer statusDel) {
		set("status_del", statusDel);
	}
	
	/**
	 * 状态（0-删除 未启用，1-未删除 已经启用）
	 */
	public java.lang.Integer getStatusDel() {
		return getInt("status_del");
	}

	/**
	 * 方案类型：0-合伙人与酒店的分成方案、1-平台与平台商的分成方案
	 */
	public void setPlanType(java.lang.Long planType) {
		set("plan_type", planType);
	}
	
	/**
	 * 方案类型：0-合伙人与酒店的分成方案、1-平台与平台商的分成方案
	 */
	public java.lang.Long getPlanType() {
		return getLong("plan_type");
	}

	/**
	 * 备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
