package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsOrderDistRecord<M extends BaseDdmsOrderDistRecord<M>> extends Model<M> implements IBean {

	/**
	 * 订单分成表，id主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 订单分成表，id主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 对应第三方订单编号
	 */
	public void setDisOrderSn(java.lang.String disOrderSn) {
		set("dis_order_sn", disOrderSn);
	}
	
	/**
	 * 对应第三方订单编号
	 */
	public java.lang.String getDisOrderSn() {
		return getStr("dis_order_sn");
	}

	/**
	 * 分账金额（元）
	 */
	public void setDisAmount(java.math.BigDecimal disAmount) {
		set("dis_amount", disAmount);
	}
	
	/**
	 * 分账金额（元）
	 */
	public java.math.BigDecimal getDisAmount() {
		return get("dis_amount");
	}

	/**
	 * 分类（0：用户分润 1:平台分润3:订单分润）
	 */
	public void setIdentityType(java.lang.Integer identityType) {
		set("identity_type", identityType);
	}
	
	/**
	 * 分类（0：用户分润 1:平台分润3:订单分润）
	 */
	public java.lang.Integer getIdentityType() {
		return getInt("identity_type");
	}

	/**
	 * 用户id
	 */
	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	/**
	 * 场所id
	 */
	public void setHotelId(java.lang.Integer hotelId) {
		set("hotel_id", hotelId);
	}
	
	/**
	 * 场所id
	 */
	public java.lang.Integer getHotelId() {
		return getInt("hotel_id");
	}

	/**
	 * 场所名称
	 */
	public void setHotelName(java.lang.String hotelName) {
		set("hotel_name", hotelName);
	}
	
	/**
	 * 场所名称
	 */
	public java.lang.String getHotelName() {
		return getStr("hotel_name");
	}

	/**
	 * 设备id
	 */
	public void setDeviceId(java.lang.Long deviceId) {
		set("device_id", deviceId);
	}
	
	/**
	 * 设备id
	 */
	public java.lang.Long getDeviceId() {
		return getLong("device_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 备注
	 */
	public void setDisNote(java.lang.String disNote) {
		set("dis_note", disNote);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getDisNote() {
		return getStr("dis_note");
	}

	/**
	 * 手续费率(%)
	 */
	public void setServiceRate(java.math.BigDecimal serviceRate) {
		set("service_rate", serviceRate);
	}
	
	/**
	 * 手续费率(%)
	 */
	public java.math.BigDecimal getServiceRate() {
		return get("service_rate");
	}

	/**
	 * 分账状态（0：转账成功、1-分账到余额、2-审核中、3-微信预付款状态）
	 */
	public void setDisStatus(java.lang.Integer disStatus) {
		set("dis_status", disStatus);
	}
	
	/**
	 * 分账状态（0：转账成功、1-分账到余额、2-审核中、3-微信预付款状态）
	 */
	public java.lang.Integer getDisStatus() {
		return getInt("dis_status");
	}

}
