package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmsAlbum<M extends BasePmsAlbum<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 相册名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 相册名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 相册封面图
	 */
	public void setCoverPic(java.lang.String coverPic) {
		set("cover_pic", coverPic);
	}
	
	/**
	 * 相册封面图
	 */
	public java.lang.String getCoverPic() {
		return getStr("cover_pic");
	}

	/**
	 * 相册中图片的数量
	 */
	public void setPicCount(java.lang.Integer picCount) {
		set("pic_count", picCount);
	}
	
	/**
	 * 相册中图片的数量
	 */
	public java.lang.Integer getPicCount() {
		return getInt("pic_count");
	}

	/**
	 * 相册排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 相册排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

}
