package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHmsHotelType<M extends BaseHmsHotelType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 酒店类型名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 酒店类型名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 酒店类型父 Id
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 酒店类型父 Id
	 */
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setPathId(java.lang.String pathId) {
		set("path_id", pathId);
	}
	
	public java.lang.String getPathId() {
		return getStr("path_id");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
