package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsMsgDailyDist<M extends BaseDdmsMsgDailyDist<M>> extends Model<M> implements IBean {

	/**
	 * 分账结果的信息记录表
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 分账结果的信息记录表
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 分账时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 分账时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 分账状态：0-未完成/失败；1-已完成/成功
	 */
	public void setStatusResult(java.lang.Long statusResult) {
		set("status_result", statusResult);
	}
	
	/**
	 * 分账状态：0-未完成/失败；1-已完成/成功
	 */
	public java.lang.Long getStatusResult() {
		return getLong("status_result");
	}

	/**
	 * 错误描述
	 */
	public void setErrorDesc(java.lang.String errorDesc) {
		set("error_desc", errorDesc);
	}
	
	/**
	 * 错误描述
	 */
	public java.lang.String getErrorDesc() {
		return getStr("error_desc");
	}

	/**
	 * 备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
