package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUmsMember<M extends BaseUmsMember<M>> extends Model<M> implements IBean {

	/**
	 * 前台用户表ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 前台用户表ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户的openid
	 */
	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}
	
	/**
	 * 用户的openid
	 */
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	/**
	 * 手机号码
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号码
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 创建时间
	 */
	public void setCreationTime(java.util.Date creationTime) {
		set("creation_time", creationTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreationTime() {
		return get("creation_time");
	}

}
