package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmsProductAlbumRelation<M extends BasePmsProductAlbumRelation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 商品 Id
	 */
	public void setProductId(java.math.BigInteger productId) {
		set("product_id", productId);
	}
	
	/**
	 * 商品 Id
	 */
	public java.math.BigInteger getProductId() {
		return get("product_id");
	}

	/**
	 * 相册 Id
	 */
	public void setAlbumId(java.math.BigInteger albumId) {
		set("album_id", albumId);
	}
	
	/**
	 * 相册 Id
	 */
	public java.math.BigInteger getAlbumId() {
		return get("album_id");
	}

	/**
	 * 删除状态（0-已删除，1-未删除）
	 */
	public void setStatusDel(java.lang.Boolean statusDel) {
		set("status_del", statusDel);
	}
	
	/**
	 * 删除状态（0-已删除，1-未删除）
	 */
	public java.lang.Boolean getStatusDel() {
		return get("status_del");
	}

}
