package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUmsAdminLoginLog<M extends BaseUmsAdminLoginLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 浏览器登录类型
	 */
	public void setUserAgent(java.lang.String userAgent) {
		set("user_agent", userAgent);
	}
	
	/**
	 * 浏览器登录类型
	 */
	public java.lang.String getUserAgent() {
		return getStr("user_agent");
	}

}
