package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUmsAdminRoleRelation<M extends BaseUmsAdminRoleRelation<M>> extends Model<M> implements IBean {

	/**
	 * 角色表关联表
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 角色表关联表
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户ID
	 */
	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	/**
	 * 角色ID
	 */
	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}
	
	/**
	 * 角色ID
	 */
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

}
