package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmsProductAdminRelation<M extends BasePmsProductAdminRelation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 商品ID
	 */
	public void setProductId(java.math.BigInteger productId) {
		set("product_id", productId);
	}
	
	/**
	 * 商品ID
	 */
	public java.math.BigInteger getProductId() {
		return get("product_id");
	}

	/**
	 * 用户ID
	 */
	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Integer getAdminId() {
		return getInt("admin_id");
	}

	/**
	 * 删除状态：1-true-未删除 0-false-已删除
	 */
	public void setStatusDel(java.lang.Boolean statusDel) {
		set("status_del", statusDel);
	}
	
	/**
	 * 删除状态：1-true-未删除 0-false-已删除
	 */
	public java.lang.Boolean getStatusDel() {
		return get("status_del");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	public java.lang.String getNote() {
		return getStr("note");
	}

}
