package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmsBrand<M extends BasePmsBrand<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 品牌名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 品牌名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 品牌首字母（小米-M、苹果-A）
	 */
	public void setFirstLetter(java.lang.String firstLetter) {
		set("first_letter", firstLetter);
	}
	
	/**
	 * 品牌首字母（小米-M、苹果-A）
	 */
	public java.lang.String getFirstLetter() {
		return getStr("first_letter");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 是否为品牌制造商：0->不是；1->是
	 */
	public void setFactoryStatus(java.lang.Integer factoryStatus) {
		set("factory_status", factoryStatus);
	}
	
	/**
	 * 是否为品牌制造商：0->不是；1->是
	 */
	public java.lang.Integer getFactoryStatus() {
		return getInt("factory_status");
	}

	/**
	 * 是否显示
	 */
	public void setShowStatus(java.lang.Integer showStatus) {
		set("show_status", showStatus);
	}
	
	/**
	 * 是否显示
	 */
	public java.lang.Integer getShowStatus() {
		return getInt("show_status");
	}

	/**
	 * 产品数量
	 */
	public void setProductCount(java.lang.Integer productCount) {
		set("product_count", productCount);
	}
	
	/**
	 * 产品数量
	 */
	public java.lang.Integer getProductCount() {
		return getInt("product_count");
	}

	/**
	 * 产品评论数量
	 */
	public void setProductCommentCount(java.lang.Integer productCommentCount) {
		set("product_comment_count", productCommentCount);
	}
	
	/**
	 * 产品评论数量
	 */
	public java.lang.Integer getProductCommentCount() {
		return getInt("product_comment_count");
	}

	/**
	 * 品牌logo
	 */
	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}
	
	/**
	 * 品牌logo
	 */
	public java.lang.String getLogo() {
		return getStr("logo");
	}

	/**
	 * 专区大图
	 */
	public void setBigPic(java.lang.String bigPic) {
		set("big_pic", bigPic);
	}
	
	/**
	 * 专区大图
	 */
	public java.lang.String getBigPic() {
		return getStr("big_pic");
	}

	/**
	 * 品牌故事
	 */
	public void setBrandStory(java.lang.String brandStory) {
		set("brand_story", brandStory);
	}
	
	/**
	 * 品牌故事
	 */
	public java.lang.String getBrandStory() {
		return getStr("brand_story");
	}

}
