package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrdersRefundTest<M extends BaseOrdersRefundTest<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderNumber(java.lang.String orderNumber) {
		set("order_number", orderNumber);
	}
	
	public java.lang.String getOrderNumber() {
		return getStr("order_number");
	}

	public void setDevId(java.lang.String devId) {
		set("dev_id", devId);
	}
	
	public java.lang.String getDevId() {
		return getStr("dev_id");
	}

	public void setMaintenanceUser(java.lang.String maintenanceUser) {
		set("maintenance_user", maintenanceUser);
	}
	
	public java.lang.String getMaintenanceUser() {
		return getStr("maintenance_user");
	}

	public void setPartnerUser(java.lang.String partnerUser) {
		set("partner_user", partnerUser);
	}
	
	public java.lang.String getPartnerUser() {
		return getStr("partner_user");
	}

	public void setPlaceName(java.lang.String placeName) {
		set("place_name", placeName);
	}
	
	public java.lang.String getPlaceName() {
		return getStr("place_name");
	}

	public void setRoomNumber(java.lang.String roomNumber) {
		set("room_number", roomNumber);
	}
	
	public java.lang.String getRoomNumber() {
		return getStr("room_number");
	}

	public void setActualPayment(java.lang.String actualPayment) {
		set("actual_payment", actualPayment);
	}
	
	public java.lang.String getActualPayment() {
		return getStr("actual_payment");
	}

	public void setCoupon(java.lang.String coupon) {
		set("coupon", coupon);
	}
	
	public java.lang.String getCoupon() {
		return getStr("coupon");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setActualPayments(java.lang.String actualPayments) {
		set("actual_payments", actualPayments);
	}
	
	public java.lang.String getActualPayments() {
		return getStr("actual_payments");
	}

	public void setPayType(java.lang.String payType) {
		set("pay_type", payType);
	}
	
	public java.lang.String getPayType() {
		return getStr("pay_type");
	}

	public void setOrderType(java.lang.String orderType) {
		set("order_type", orderType);
	}
	
	public java.lang.String getOrderType() {
		return getStr("order_type");
	}

	public void setNumbers(java.lang.String numbers) {
		set("numbers", numbers);
	}
	
	public java.lang.String getNumbers() {
		return getStr("numbers");
	}

	public void setTimePayment(java.util.Date timePayment) {
		set("time_payment", timePayment);
	}
	
	public java.util.Date getTimePayment() {
		return get("time_payment");
	}

	public void setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
	}
	
	public java.util.Date getOrderTime() {
		return get("order_time");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public void setContainerNumber(java.lang.String containerNumber) {
		set("container_number", containerNumber);
	}
	
	public java.lang.String getContainerNumber() {
		return getStr("container_number");
	}

	public void setCommodityPrice(java.lang.String commodityPrice) {
		set("commodity_price", commodityPrice);
	}
	
	public java.lang.String getCommodityPrice() {
		return getStr("commodity_price");
	}

	public void setQuantity(java.lang.String quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.String getQuantity() {
		return getStr("quantity");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}
	
	public java.lang.String getPrice() {
		return getStr("price");
	}

	public void setUserBd(java.lang.String userBd) {
		set("user_bd", userBd);
	}
	
	public java.lang.String getUserBd() {
		return getStr("user_bd");
	}

}
