package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHmsHotelDevice<M extends BaseHmsHotelDevice<M>> extends Model<M> implements IBean {

	/**
	 * 酒店与设备的绑定表Id
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 酒店与设备的绑定表Id
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 酒店ID
	 */
	public void setHotelId(java.lang.Long hotelId) {
		set("hotel_id", hotelId);
	}
	
	/**
	 * 酒店ID
	 */
	public java.lang.Long getHotelId() {
		return getLong("hotel_id");
	}

	/**
	 * 设备Id
	 */
	public void setDevId(java.math.BigInteger devId) {
		set("dev_id", devId);
	}
	
	/**
	 * 设备Id
	 */
	public java.math.BigInteger getDevId() {
		return get("dev_id");
	}

	/**
	 * 酒店管理员Id(不是这个酒店的负责人（店长），负责人没有账号)
	 */
	public void setHotelAdminId(java.math.BigInteger hotelAdminId) {
		set("hotel_admin_id", hotelAdminId);
	}
	
	/**
	 * 酒店管理员Id(不是这个酒店的负责人（店长），负责人没有账号)
	 */
	public java.math.BigInteger getHotelAdminId() {
		return get("hotel_admin_id");
	}

	/**
	 * 房间号
	 */
	public void setRoomNo(java.lang.String roomNo) {
		set("room_no", roomNo);
	}
	
	/**
	 * 房间号
	 */
	public java.lang.String getRoomNo() {
		return getStr("room_no");
	}

	/**
	 * 房间位置
	 */
	public void setRoomLocal(java.lang.String roomLocal) {
		set("room_local", roomLocal);
	}
	
	/**
	 * 房间位置
	 */
	public java.lang.String getRoomLocal() {
		return getStr("room_local");
	}

	/**
	 * 绑定时间
	 */
	public void setBindTime(java.util.Date bindTime) {
		set("bind_time", bindTime);
	}
	
	/**
	 * 绑定时间
	 */
	public java.util.Date getBindTime() {
		return get("bind_time");
	}

	/**
	 * 绑定状态（0-未绑定、1-已绑定、2-留作扩展）
	 */
	public void setStatusBind(java.lang.Integer statusBind) {
		set("status_bind", statusBind);
	}
	
	/**
	 * 绑定状态（0-未绑定、1-已绑定、2-留作扩展）
	 */
	public java.lang.Integer getStatusBind() {
		return getInt("status_bind");
	}

	/**
	 * 删除状态（1-true-未删除、0-false-已删除）
	 */
	public void setStatusDel(java.lang.Boolean statusDel) {
		set("status_del", statusDel);
	}
	
	/**
	 * 删除状态（1-true-未删除、0-false-已删除）
	 */
	public java.lang.Boolean getStatusDel() {
		return get("status_del");
	}

	/**
	 * 是否为投资设备（1-true-是投资设备，0-false-非投资设备）
	 */
	public void setStatusInvest(java.lang.Boolean statusInvest) {
		set("status_invest", statusInvest);
	}
	
	/**
	 * 是否为投资设备（1-true-是投资设备，0-false-非投资设备）
	 */
	public java.lang.Boolean getStatusInvest() {
		return get("status_invest");
	}

}
