package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmsProductPictureRelation<M extends BasePmsProductPictureRelation<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 商品 Id
	 */
	public void setProductId(java.math.BigInteger productId) {
		set("product_id", productId);
	}
	
	/**
	 * 商品 Id
	 */
	public java.math.BigInteger getProductId() {
		return get("product_id");
	}

	/**
	 * 图片 Id
	 */
	public void setPicId(java.math.BigInteger picId) {
		set("pic_id", picId);
	}
	
	/**
	 * 图片 Id
	 */
	public java.math.BigInteger getPicId() {
		return get("pic_id");
	}

}
