package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUmsRoleResourceRelation<M extends BaseUmsRoleResourceRelation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 角色ID
	 */
	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}
	
	/**
	 * 角色ID
	 */
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

	/**
	 * 资源ID
	 */
	public void setResourceId(java.lang.Long resourceId) {
		set("resource_id", resourceId);
	}
	
	/**
	 * 资源ID
	 */
	public java.lang.Long getResourceId() {
		return getLong("resource_id");
	}

}
