package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUmsRole<M extends BaseUmsRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 后台用户数量
	 */
	public void setAdminCount(java.lang.Integer adminCount) {
		set("admin_count", adminCount);
	}
	
	/**
	 * 后台用户数量
	 */
	public java.lang.Integer getAdminCount() {
		return getInt("admin_count");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 启用状态：0->禁用；1->启用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 启用状态：0->禁用；1->启用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 说明
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 说明
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
