package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmsProduct<M extends BasePmsProduct<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 商品名称
	 */
	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	/**
	 * 品牌 Id
	 */
	public void setBrandId(java.lang.Long brandId) {
		set("brand_id", brandId);
	}
	
	/**
	 * 品牌 Id
	 */
	public java.lang.Long getBrandId() {
		return getLong("brand_id");
	}

	/**
	 * 品牌名称
	 */
	public void setBrandName(java.lang.String brandName) {
		set("brand_name", brandName);
	}
	
	/**
	 * 品牌名称
	 */
	public java.lang.String getBrandName() {
		return getStr("brand_name");
	}

	/**
	 * 产品分类 Id
	 */
	public void setProductCategoryId(java.lang.Long productCategoryId) {
		set("product_category_id", productCategoryId);
	}
	
	/**
	 * 产品分类 Id
	 */
	public java.lang.Long getProductCategoryId() {
		return getLong("product_category_id");
	}

	/**
	 * 商品分类名称
	 */
	public void setProductCategoryName(java.lang.String productCategoryName) {
		set("product_category_name", productCategoryName);
	}
	
	/**
	 * 商品分类名称
	 */
	public java.lang.String getProductCategoryName() {
		return getStr("product_category_name");
	}

	/**
	 * 副标题（即：商品的简短描述）
	 */
	public void setSubTitle(java.lang.String subTitle) {
		set("sub_title", subTitle);
	}
	
	/**
	 * 副标题（即：商品的简短描述）
	 */
	public java.lang.String getSubTitle() {
		return getStr("sub_title");
	}

	/**
	 * 货号（商品编号）
	 */
	public void setProductSn(java.lang.String productSn) {
		set("product_sn", productSn);
	}
	
	/**
	 * 货号（商品编号）
	 */
	public java.lang.String getProductSn() {
		return getStr("product_sn");
	}

	/**
	 * 商品图片（主）
	 */
	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}
	
	/**
	 * 商品图片（主）
	 */
	public java.lang.String getPic() {
		return getStr("pic");
	}

	/**
	 * 画册图片，连产品图片限制为5张，以逗号分割
	 */
	public void setAlbumPics(java.lang.String albumPics) {
		set("album_pics", albumPics);
	}
	
	/**
	 * 画册图片，连产品图片限制为5张，以逗号分割
	 */
	public java.lang.String getAlbumPics() {
		return getStr("album_pics");
	}

	/**
	 * 商品规格类型（1）
	 */
	public void setSpecType(java.lang.String specType) {
		set("spec_type", specType);
	}
	
	/**
	 * 商品规格类型（1）
	 */
	public java.lang.String getSpecType() {
		return getStr("spec_type");
	}

	/**
	 * 分成方式：1-营业额分成；2-利润分成（1）
	 */
	public void setDivideMode(java.lang.Integer divideMode) {
		set("divide_mode", divideMode);
	}
	
	/**
	 * 分成方式：1-营业额分成；2-利润分成（1）
	 */
	public java.lang.Integer getDivideMode() {
		return getInt("divide_mode");
	}

	/**
	 * 价格（售价）
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 价格（售价）
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 价格（进货价）(1)
	 */
	public void setPriceOrder(java.math.BigDecimal priceOrder) {
		set("price_order", priceOrder);
	}
	
	/**
	 * 价格（进货价）(1)
	 */
	public java.math.BigDecimal getPriceOrder() {
		return get("price_order");
	}

	/**
	 * 价格（下级进货价）(1)
	 */
	public void setPriceLower(java.lang.String priceLower) {
		set("price_lower", priceLower);
	}
	
	/**
	 * 价格（下级进货价）(1)
	 */
	public java.lang.String getPriceLower() {
		return getStr("price_lower");
	}

	/**
	 * 市场价
	 */
	public void setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
	}
	
	/**
	 * 市场价
	 */
	public java.math.BigDecimal getOriginalPrice() {
		return get("original_price");
	}

	/**
	 * 促销价格
	 */
	public void setPromotionPrice(java.math.BigDecimal promotionPrice) {
		set("promotion_price", promotionPrice);
	}
	
	/**
	 * 促销价格
	 */
	public java.math.BigDecimal getPromotionPrice() {
		return get("promotion_price");
	}

	/**
	 * 销量（基础销量）
	 */
	public void setSale(java.lang.Integer sale) {
		set("sale", sale);
	}
	
	/**
	 * 销量（基础销量）
	 */
	public java.lang.Integer getSale() {
		return getInt("sale");
	}

	/**
	 * 库存（实际在库数-实际库存）
	 */
	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}
	
	/**
	 * 库存（实际在库数-实际库存）
	 */
	public java.lang.Integer getStock() {
		return getInt("stock");
	}

	/**
	 * 商品配品
	 */
	public void setSaleWith(java.lang.String saleWith) {
		set("sale_with", saleWith);
	}
	
	/**
	 * 商品配品
	 */
	public java.lang.String getSaleWith() {
		return getStr("sale_with");
	}

	/**
	 * 库存预警值
	 */
	public void setLowStock(java.lang.Integer lowStock) {
		set("low_stock", lowStock);
	}
	
	/**
	 * 库存预警值
	 */
	public java.lang.Integer getLowStock() {
		return getInt("low_stock");
	}

	/**
	 * 详情标题
	 */
	public void setDetailTitle(java.lang.String detailTitle) {
		set("detail_title", detailTitle);
	}
	
	/**
	 * 详情标题
	 */
	public java.lang.String getDetailTitle() {
		return getStr("detail_title");
	}

	/**
	 * 详情描述
	 */
	public void setDetailDesc(java.lang.String detailDesc) {
		set("detail_desc", detailDesc);
	}
	
	/**
	 * 详情描述
	 */
	public java.lang.String getDetailDesc() {
		return getStr("detail_desc");
	}

	/**
	 * 商品描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 商品描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 删除状态：0->未删除；1->已删除
	 */
	public void setDeleteStatus(java.lang.Integer deleteStatus) {
		set("delete_status", deleteStatus);
	}
	
	/**
	 * 删除状态：0->未删除；1->已删除
	 */
	public java.lang.Integer getDeleteStatus() {
		return getInt("delete_status");
	}

	/**
	 * 是否为测试商品：0->不是测试产品；1true->是测试产品
	 */
	public void setIsTest(java.lang.Boolean isTest) {
		set("is_test", isTest);
	}
	
	/**
	 * 是否为测试商品：0->不是测试产品；1true->是测试产品
	 */
	public java.lang.Boolean getIsTest() {
		return get("is_test");
	}

	/**
	 * 是否为虚拟商品：0->不是虚拟产品；1->是虚拟产品
	 */
	public void setIsVirtual(java.lang.Boolean isVirtual) {
		set("is_virtual", isVirtual);
	}
	
	/**
	 * 是否为虚拟商品：0->不是虚拟产品；1->是虚拟产品
	 */
	public java.lang.Boolean getIsVirtual() {
		return get("is_virtual");
	}

	/**
	 * 关键字（商品标签）
	 */
	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}
	
	/**
	 * 关键字（商品标签）
	 */
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	/**
	 * 商品入库时间
	 */
	public void setPutTime(java.util.Date putTime) {
		set("put_time", putTime);
	}
	
	/**
	 * 商品入库时间
	 */
	public java.util.Date getPutTime() {
		return get("put_time");
	}

	/**
	 * 新品状态:0->不是新品；1->新品
	 */
	public void setNewStatus(java.lang.Integer newStatus) {
		set("new_status", newStatus);
	}
	
	/**
	 * 新品状态:0->不是新品；1->新品
	 */
	public java.lang.Integer getNewStatus() {
		return getInt("new_status");
	}

	/**
	 * 推荐状态；0->不推荐；1->推荐
	 */
	public void setRecommandStatus(java.lang.Integer recommandStatus) {
		set("recommand_status", recommandStatus);
	}
	
	/**
	 * 推荐状态；0->不推荐；1->推荐
	 */
	public java.lang.Integer getRecommandStatus() {
		return getInt("recommand_status");
	}

	/**
	 * 审核状态：0->未审核；1->审核通过
	 */
	public void setVerifyStatus(java.lang.Integer verifyStatus) {
		set("verify_status", verifyStatus);
	}
	
	/**
	 * 审核状态：0->未审核；1->审核通过
	 */
	public java.lang.Integer getVerifyStatus() {
		return getInt("verify_status");
	}

	/**
	 * 上架状态：0->下架；1->上架
	 */
	public void setPublishStatus(java.lang.Integer publishStatus) {
		set("publish_status", publishStatus);
	}
	
	/**
	 * 上架状态：0->下架；1->上架
	 */
	public java.lang.Integer getPublishStatus() {
		return getInt("publish_status");
	}

	/**
	 * 营销备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 营销备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

	/**
	 * 运费模版 Id
	 */
	public void setFeightTemplateId(java.lang.Long feightTemplateId) {
		set("feight_template_id", feightTemplateId);
	}
	
	/**
	 * 运费模版 Id
	 */
	public java.lang.Long getFeightTemplateId() {
		return getLong("feight_template_id");
	}

	/**
	 * 产品属性分类 Id
	 */
	public void setProductAttributeCategoryId(java.lang.Long productAttributeCategoryId) {
		set("product_attribute_category_id", productAttributeCategoryId);
	}
	
	/**
	 * 产品属性分类 Id
	 */
	public java.lang.Long getProductAttributeCategoryId() {
		return getLong("product_attribute_category_id");
	}

	/**
	 * 赠送的成长值
	 */
	public void setGiftGrowth(java.lang.Integer giftGrowth) {
		set("gift_growth", giftGrowth);
	}
	
	/**
	 * 赠送的成长值
	 */
	public java.lang.Integer getGiftGrowth() {
		return getInt("gift_growth");
	}

	/**
	 * 赠送的积分
	 */
	public void setGiftPoint(java.lang.Integer giftPoint) {
		set("gift_point", giftPoint);
	}
	
	/**
	 * 赠送的积分
	 */
	public java.lang.Integer getGiftPoint() {
		return getInt("gift_point");
	}

	/**
	 * 限制使用的积分数
	 */
	public void setUsePointLimit(java.lang.Integer usePointLimit) {
		set("use_point_limit", usePointLimit);
	}
	
	/**
	 * 限制使用的积分数
	 */
	public java.lang.Integer getUsePointLimit() {
		return getInt("use_point_limit");
	}

	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	/**
	 * 商品重量，默认为克
	 */
	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}
	
	/**
	 * 商品重量，默认为克
	 */
	public java.math.BigDecimal getWeight() {
		return get("weight");
	}

	/**
	 * 是否为预告商品：0->不是；1->是
	 */
	public void setPreviewStatus(java.lang.Integer previewStatus) {
		set("preview_status", previewStatus);
	}
	
	/**
	 * 是否为预告商品：0->不是；1->是
	 */
	public java.lang.Integer getPreviewStatus() {
		return getInt("preview_status");
	}

	/**
	 * 以逗号分割的产品服务：1->无忧退货；2->快速退款；3->免费包邮
	 */
	public void setServiceIds(java.lang.String serviceIds) {
		set("service_ids", serviceIds);
	}
	
	/**
	 * 以逗号分割的产品服务：1->无忧退货；2->快速退款；3->免费包邮
	 */
	public java.lang.String getServiceIds() {
		return getStr("service_ids");
	}

	/**
	 * 产品详情网页内容
	 */
	public void setDetailHtml(java.lang.String detailHtml) {
		set("detail_html", detailHtml);
	}
	
	/**
	 * 产品详情网页内容
	 */
	public java.lang.String getDetailHtml() {
		return getStr("detail_html");
	}

	/**
	 * 移动端网页详情
	 */
	public void setDetailMobileHtml(java.lang.String detailMobileHtml) {
		set("detail_mobile_html", detailMobileHtml);
	}
	
	/**
	 * 移动端网页详情
	 */
	public java.lang.String getDetailMobileHtml() {
		return getStr("detail_mobile_html");
	}

	/**
	 * 促销开始时间
	 */
	public void setPromotionStartTime(java.util.Date promotionStartTime) {
		set("promotion_start_time", promotionStartTime);
	}
	
	/**
	 * 促销开始时间
	 */
	public java.util.Date getPromotionStartTime() {
		return get("promotion_start_time");
	}

	/**
	 * 促销结束时间
	 */
	public void setPromotionEndTime(java.util.Date promotionEndTime) {
		set("promotion_end_time", promotionEndTime);
	}
	
	/**
	 * 促销结束时间
	 */
	public java.util.Date getPromotionEndTime() {
		return get("promotion_end_time");
	}

	/**
	 * 活动限购数量
	 */
	public void setPromotionPerLimit(java.lang.Integer promotionPerLimit) {
		set("promotion_per_limit", promotionPerLimit);
	}
	
	/**
	 * 活动限购数量
	 */
	public java.lang.Integer getPromotionPerLimit() {
		return getInt("promotion_per_limit");
	}

	/**
	 * 促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->限时购
	 */
	public void setPromotionType(java.lang.Integer promotionType) {
		set("promotion_type", promotionType);
	}
	
	/**
	 * 促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->限时购
	 */
	public java.lang.Integer getPromotionType() {
		return getInt("promotion_type");
	}

}
