package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOmsOrder<M extends BaseOmsOrder<M>> extends Model<M> implements IBean {

	/**
	 * 订单id
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 订单id
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 场所id
	 */
	public void setHotelId(java.lang.Integer hotelId) {
		set("hotel_id", hotelId);
	}
	
	/**
	 * 场所id
	 */
	public java.lang.Integer getHotelId() {
		return getInt("hotel_id");
	}

	/**
	 * 场所名称
	 */
	public void setHotelName(java.lang.String hotelName) {
		set("hotel_name", hotelName);
	}
	
	/**
	 * 场所名称
	 */
	public java.lang.String getHotelName() {
		return getStr("hotel_name");
	}

	/**
	 * 房间号
	 */
	public void setRoomNo(java.lang.String roomNo) {
		set("room_no", roomNo);
	}
	
	/**
	 * 房间号
	 */
	public java.lang.String getRoomNo() {
		return getStr("room_no");
	}

	/**
	 * 设备id
	 */
	public void setDeviceId(java.math.BigInteger deviceId) {
		set("device_id", deviceId);
	}
	
	/**
	 * 设备id
	 */
	public java.math.BigInteger getDeviceId() {
		return get("device_id");
	}

	/**
	 * 订单编号(自己生成的订单号)
	 */
	public void setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
	}
	
	/**
	 * 订单编号(自己生成的订单号)
	 */
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	/**
	 * 订单总金额
	 */
	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
	}
	
	/**
	 * 订单总金额
	 */
	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	/**
	 * 应付金额（实际支付金额）
	 */
	public void setPayAmount(java.math.BigDecimal payAmount) {
		set("pay_amount", payAmount);
	}
	
	/**
	 * 应付金额（实际支付金额）
	 */
	public java.math.BigDecimal getPayAmount() {
		return get("pay_amount");
	}

	/**
	 * 支付方式：0->未支付；1->支付宝；2->微信
	 */
	public void setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
	}
	
	/**
	 * 支付方式：0->未支付；1->支付宝；2->微信
	 */
	public java.lang.Integer getPayType() {
		return getInt("pay_type");
	}

	/**
	 * 订单来源：0->PC订单；1->app订单；2->小程序订单
	 */
	public void setSourceType(java.lang.Integer sourceType) {
		set("source_type", sourceType);
	}
	
	/**
	 * 订单来源：0->PC订单；1->app订单；2->小程序订单
	 */
	public java.lang.Integer getSourceType() {
		return getInt("source_type");
	}

	/**
	 * 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单；6->已支付；7->申请退款8-退款成功
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单；6->已支付；7->申请退款8-退款成功
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 分账状态：0->未分账；1->已分账；2->分账失败
	 */
	public void setDistStatus(java.lang.Long distStatus) {
		set("dist_status", distStatus);
	}
	
	/**
	 * 分账状态：0->未分账；1->已分账；2->分账失败
	 */
	public java.lang.Long getDistStatus() {
		return getLong("dist_status");
	}

	/**
	 * 订单类型：0->正常订单；1->秒杀订单
	 */
	public void setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
	}
	
	/**
	 * 订单类型：0->正常订单；1->秒杀订单
	 */
	public java.lang.Integer getOrderType() {
		return getInt("order_type");
	}

	/**
	 * 删除状态：0->未删除；1->已删除
	 */
	public void setDeleteStatus(java.lang.Long deleteStatus) {
		set("delete_status", deleteStatus);
	}
	
	/**
	 * 删除状态：0->未删除；1->已删除
	 */
	public java.lang.Long getDeleteStatus() {
		return getLong("delete_status");
	}

	/**
	 * 交易单号（微信返回的交易单号）
	 */
	public void setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
	}
	
	/**
	 * 交易单号（微信返回的交易单号）
	 */
	public java.lang.String getTransactionId() {
		return getStr("transaction_id");
	}

	/**
	 * 支付时间
	 */
	public void setPaymentTime(java.util.Date paymentTime) {
		set("payment_time", paymentTime);
	}
	
	/**
	 * 支付时间
	 */
	public java.util.Date getPaymentTime() {
		return get("payment_time");
	}

	/**
	 * 用户的唯一标识
	 */
	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}
	
	/**
	 * 用户的唯一标识
	 */
	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	/**
	 * 会员id
	 */
	public void setMemberId(java.lang.Long memberId) {
		set("member_id", memberId);
	}
	
	/**
	 * 会员id
	 */
	public java.lang.Long getMemberId() {
		return getLong("member_id");
	}

	/**
	 * 提交时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 提交时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 用户帐号
	 */
	public void setMemberUsername(java.lang.String memberUsername) {
		set("member_username", memberUsername);
	}
	
	/**
	 * 用户帐号
	 */
	public java.lang.String getMemberUsername() {
		return getStr("member_username");
	}

	/**
	 * 优惠券id
	 */
	public void setCouponId(java.lang.Long couponId) {
		set("coupon_id", couponId);
	}
	
	/**
	 * 优惠券id
	 */
	public java.lang.Long getCouponId() {
		return getLong("coupon_id");
	}

	/**
	 * 运费金额
	 */
	public void setFreightAmount(java.math.BigDecimal freightAmount) {
		set("freight_amount", freightAmount);
	}
	
	/**
	 * 运费金额
	 */
	public java.math.BigDecimal getFreightAmount() {
		return get("freight_amount");
	}

	/**
	 * 促销优化金额（促销价、满减、阶梯价）
	 */
	public void setPromotionAmount(java.math.BigDecimal promotionAmount) {
		set("promotion_amount", promotionAmount);
	}
	
	/**
	 * 促销优化金额（促销价、满减、阶梯价）
	 */
	public java.math.BigDecimal getPromotionAmount() {
		return get("promotion_amount");
	}

	/**
	 * 积分抵扣金额
	 */
	public void setIntegrationAmount(java.math.BigDecimal integrationAmount) {
		set("integration_amount", integrationAmount);
	}
	
	/**
	 * 积分抵扣金额
	 */
	public java.math.BigDecimal getIntegrationAmount() {
		return get("integration_amount");
	}

	/**
	 * 优惠券抵扣金额
	 */
	public void setCouponAmount(java.math.BigDecimal couponAmount) {
		set("coupon_amount", couponAmount);
	}
	
	/**
	 * 优惠券抵扣金额
	 */
	public java.math.BigDecimal getCouponAmount() {
		return get("coupon_amount");
	}

	/**
	 * 管理员后台调整订单使用的折扣金额
	 */
	public void setDiscountAmount(java.math.BigDecimal discountAmount) {
		set("discount_amount", discountAmount);
	}
	
	/**
	 * 管理员后台调整订单使用的折扣金额
	 */
	public java.math.BigDecimal getDiscountAmount() {
		return get("discount_amount");
	}

	/**
	 * 物流公司(配送方式)
	 */
	public void setDeliveryCompany(java.lang.String deliveryCompany) {
		set("delivery_company", deliveryCompany);
	}
	
	/**
	 * 物流公司(配送方式)
	 */
	public java.lang.String getDeliveryCompany() {
		return getStr("delivery_company");
	}

	/**
	 * 物流单号
	 */
	public void setDeliverySn(java.lang.String deliverySn) {
		set("delivery_sn", deliverySn);
	}
	
	/**
	 * 物流单号
	 */
	public java.lang.String getDeliverySn() {
		return getStr("delivery_sn");
	}

	/**
	 * 自动确认时间（天）
	 */
	public void setAutoConfirmDay(java.lang.Integer autoConfirmDay) {
		set("auto_confirm_day", autoConfirmDay);
	}
	
	/**
	 * 自动确认时间（天）
	 */
	public java.lang.Integer getAutoConfirmDay() {
		return getInt("auto_confirm_day");
	}

	/**
	 * 可以获得的积分
	 */
	public void setIntegration(java.lang.Integer integration) {
		set("integration", integration);
	}
	
	/**
	 * 可以获得的积分
	 */
	public java.lang.Integer getIntegration() {
		return getInt("integration");
	}

	/**
	 * 可以活动的成长值
	 */
	public void setGrowth(java.lang.Integer growth) {
		set("growth", growth);
	}
	
	/**
	 * 可以活动的成长值
	 */
	public java.lang.Integer getGrowth() {
		return getInt("growth");
	}

	/**
	 * 活动信息
	 */
	public void setPromotionInfo(java.lang.String promotionInfo) {
		set("promotion_info", promotionInfo);
	}
	
	/**
	 * 活动信息
	 */
	public java.lang.String getPromotionInfo() {
		return getStr("promotion_info");
	}

	/**
	 * 发票类型：0->不开发票；1->电子发票；2->纸质发票
	 */
	public void setBillType(java.lang.Integer billType) {
		set("bill_type", billType);
	}
	
	/**
	 * 发票类型：0->不开发票；1->电子发票；2->纸质发票
	 */
	public java.lang.Integer getBillType() {
		return getInt("bill_type");
	}

	/**
	 * 发票抬头
	 */
	public void setBillHeader(java.lang.String billHeader) {
		set("bill_header", billHeader);
	}
	
	/**
	 * 发票抬头
	 */
	public java.lang.String getBillHeader() {
		return getStr("bill_header");
	}

	/**
	 * 发票内容
	 */
	public void setBillContent(java.lang.String billContent) {
		set("bill_content", billContent);
	}
	
	/**
	 * 发票内容
	 */
	public java.lang.String getBillContent() {
		return getStr("bill_content");
	}

	/**
	 * 收票人电话
	 */
	public void setBillReceiverPhone(java.lang.String billReceiverPhone) {
		set("bill_receiver_phone", billReceiverPhone);
	}
	
	/**
	 * 收票人电话
	 */
	public java.lang.String getBillReceiverPhone() {
		return getStr("bill_receiver_phone");
	}

	/**
	 * 收票人邮箱
	 */
	public void setBillReceiverEmail(java.lang.String billReceiverEmail) {
		set("bill_receiver_email", billReceiverEmail);
	}
	
	/**
	 * 收票人邮箱
	 */
	public java.lang.String getBillReceiverEmail() {
		return getStr("bill_receiver_email");
	}

	/**
	 * 收货人姓名
	 */
	public void setReceiverName(java.lang.String receiverName) {
		set("receiver_name", receiverName);
	}
	
	/**
	 * 收货人姓名
	 */
	public java.lang.String getReceiverName() {
		return getStr("receiver_name");
	}

	/**
	 * 收货人电话
	 */
	public void setReceiverPhone(java.lang.String receiverPhone) {
		set("receiver_phone", receiverPhone);
	}
	
	/**
	 * 收货人电话
	 */
	public java.lang.String getReceiverPhone() {
		return getStr("receiver_phone");
	}

	/**
	 * 收货人邮编
	 */
	public void setReceiverPostCode(java.lang.String receiverPostCode) {
		set("receiver_post_code", receiverPostCode);
	}
	
	/**
	 * 收货人邮编
	 */
	public java.lang.String getReceiverPostCode() {
		return getStr("receiver_post_code");
	}

	/**
	 * 省份/直辖市
	 */
	public void setReceiverProvince(java.lang.String receiverProvince) {
		set("receiver_province", receiverProvince);
	}
	
	/**
	 * 省份/直辖市
	 */
	public java.lang.String getReceiverProvince() {
		return getStr("receiver_province");
	}

	/**
	 * 城市
	 */
	public void setReceiverCity(java.lang.String receiverCity) {
		set("receiver_city", receiverCity);
	}
	
	/**
	 * 城市
	 */
	public java.lang.String getReceiverCity() {
		return getStr("receiver_city");
	}

	/**
	 * 区
	 */
	public void setReceiverRegion(java.lang.String receiverRegion) {
		set("receiver_region", receiverRegion);
	}
	
	/**
	 * 区
	 */
	public java.lang.String getReceiverRegion() {
		return getStr("receiver_region");
	}

	/**
	 * 详细地址
	 */
	public void setReceiverDetailAddress(java.lang.String receiverDetailAddress) {
		set("receiver_detail_address", receiverDetailAddress);
	}
	
	/**
	 * 详细地址
	 */
	public java.lang.String getReceiverDetailAddress() {
		return getStr("receiver_detail_address");
	}

	/**
	 * 订单备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 订单备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

	/**
	 * 确认收货状态：0->未确认；1->已确认
	 */
	public void setConfirmStatus(java.lang.Integer confirmStatus) {
		set("confirm_status", confirmStatus);
	}
	
	/**
	 * 确认收货状态：0->未确认；1->已确认
	 */
	public java.lang.Integer getConfirmStatus() {
		return getInt("confirm_status");
	}

	/**
	 * 下单时使用的积分
	 */
	public void setUseIntegration(java.lang.Integer useIntegration) {
		set("use_integration", useIntegration);
	}
	
	/**
	 * 下单时使用的积分
	 */
	public java.lang.Integer getUseIntegration() {
		return getInt("use_integration");
	}

	/**
	 * 发货时间
	 */
	public void setDeliveryTime(java.util.Date deliveryTime) {
		set("delivery_time", deliveryTime);
	}
	
	/**
	 * 发货时间
	 */
	public java.util.Date getDeliveryTime() {
		return get("delivery_time");
	}

	/**
	 * 确认收货时间
	 */
	public void setReceiveTime(java.util.Date receiveTime) {
		set("receive_time", receiveTime);
	}
	
	/**
	 * 确认收货时间
	 */
	public java.util.Date getReceiveTime() {
		return get("receive_time");
	}

	/**
	 * 评价时间
	 */
	public void setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
	}
	
	/**
	 * 评价时间
	 */
	public java.util.Date getCommentTime() {
		return get("comment_time");
	}

	/**
	 * 修改时间
	 */
	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	/**
	 * 微信支付返回的（分）金额
	 */
	public void setWxAmount(java.lang.String wxAmount) {
		set("wx_amount", wxAmount);
	}
	
	/**
	 * 微信支付返回的（分）金额
	 */
	public java.lang.String getWxAmount() {
		return getStr("wx_amount");
	}

}
