package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHmsHotel<M extends BaseHmsHotel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 场所名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 场所名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 场所类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 场所类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 省份/直辖市
	 */
	public void setAddrProvince(java.lang.String addrProvince) {
		set("addr_province", addrProvince);
	}
	
	/**
	 * 省份/直辖市
	 */
	public java.lang.String getAddrProvince() {
		return getStr("addr_province");
	}

	/**
	 * 城市
	 */
	public void setAddrCity(java.lang.String addrCity) {
		set("addr_city", addrCity);
	}
	
	/**
	 * 城市
	 */
	public java.lang.String getAddrCity() {
		return getStr("addr_city");
	}

	/**
	 * 纬度
	 */
	public void setLocalLati(java.lang.String localLati) {
		set("local_lati", localLati);
	}
	
	/**
	 * 纬度
	 */
	public java.lang.String getLocalLati() {
		return getStr("local_lati");
	}

	/**
	 * 经度
	 */
	public void setLocalLngi(java.lang.String localLngi) {
		set("local_lngi", localLngi);
	}
	
	/**
	 * 经度
	 */
	public java.lang.String getLocalLngi() {
		return getStr("local_lngi");
	}

	/**
	 * 场所定位
	 */
	public void setLocalPosition(java.lang.String localPosition) {
		set("local_position", localPosition);
	}
	
	/**
	 * 场所定位
	 */
	public java.lang.String getLocalPosition() {
		return getStr("local_position");
	}

	/**
	 * 客房价格区间
	 */
	public void setPriceRange(java.lang.Integer priceRange) {
		set("price_range", priceRange);
	}
	
	/**
	 * 客房价格区间
	 */
	public java.lang.Integer getPriceRange() {
		return getInt("price_range");
	}

	/**
	 * 位置地段
	 */
	public void setLocation(java.lang.Integer location) {
		set("location", location);
	}
	
	/**
	 * 位置地段
	 */
	public java.lang.Integer getLocation() {
		return getInt("location");
	}

	/**
	 * 房间数量
	 */
	public void setRoomNum(java.lang.Integer roomNum) {
		set("room_num", roomNum);
	}
	
	/**
	 * 房间数量
	 */
	public java.lang.Integer getRoomNum() {
		return getInt("room_num");
	}

	/**
	 * 本次投放的设备数量
	 */
	public void setDeviceNum(java.lang.Integer deviceNum) {
		set("device_num", deviceNum);
	}
	
	/**
	 * 本次投放的设备数量
	 */
	public java.lang.Integer getDeviceNum() {
		return getInt("device_num");
	}

	/**
	 * 场所负责人
	 */
	public void setCharge(java.lang.String charge) {
		set("charge", charge);
	}
	
	/**
	 * 场所负责人
	 */
	public java.lang.String getCharge() {
		return getStr("charge");
	}

	/**
	 * 负责人手机号
	 */
	public void setChargePhone(java.lang.String chargePhone) {
		set("charge_phone", chargePhone);
	}
	
	/**
	 * 负责人手机号
	 */
	public java.lang.String getChargePhone() {
		return getStr("charge_phone");
	}

	/**
	 * 场所座机（固定电话）
	 */
	public void setFixedPhone(java.lang.String fixedPhone) {
		set("fixed_phone", fixedPhone);
	}
	
	/**
	 * 场所座机（固定电话）
	 */
	public java.lang.String getFixedPhone() {
		return getStr("fixed_phone");
	}

	/**
	 * 是否设置WiFi（0-false-未设置，1-true-已设置）
	 */
	public void setSetWifi(java.lang.Boolean setWifi) {
		set("set_wifi", setWifi);
	}
	
	/**
	 * 是否设置WiFi（0-false-未设置，1-true-已设置）
	 */
	public java.lang.Boolean getSetWifi() {
		return get("set_wifi");
	}

	/**
	 * 删除状态标志（0-false-已删除，1-true-未删除）
	 */
	public void setDelStatus(java.lang.Boolean delStatus) {
		set("del_status", delStatus);
	}
	
	/**
	 * 删除状态标志（0-false-已删除，1-true-未删除）
	 */
	public java.lang.Boolean getDelStatus() {
		return get("del_status");
	}

	/**
	 * 创建时间
	 */
	public void setCreationTime(java.util.Date creationTime) {
		set("creation_time", creationTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreationTime() {
		return get("creation_time");
	}

}
