package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsProfitRecord<M extends BaseDdmsProfitRecord<M>> extends Model<M> implements IBean {

	/**
	 * 分账记录表Id(我没用)
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 分账记录表Id(我没用)
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户id
	 */
	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	/**
	 * 所属商户
	 */
	public void setDisPlatformId(java.lang.String disPlatformId) {
		set("dis_platform_id", disPlatformId);
	}
	
	/**
	 * 所属商户
	 */
	public java.lang.String getDisPlatformId() {
		return getStr("dis_platform_id");
	}

	/**
	 * 对应第三方订单编号
	 */
	public void setDisOrderSn(java.lang.String disOrderSn) {
		set("dis_order_sn", disOrderSn);
	}
	
	/**
	 * 对应第三方订单编号
	 */
	public java.lang.String getDisOrderSn() {
		return getStr("dis_order_sn");
	}

	/**
	 * 分账金额（元）
	 */
	public void setDisAmount(java.math.BigDecimal disAmount) {
		set("dis_amount", disAmount);
	}
	
	/**
	 * 分账金额（元）
	 */
	public java.math.BigDecimal getDisAmount() {
		return get("dis_amount");
	}

	/**
	 * 手续费率(%)
	 */
	public void setServiceRate(java.math.BigDecimal serviceRate) {
		set("service_rate", serviceRate);
	}
	
	/**
	 * 手续费率(%)
	 */
	public java.math.BigDecimal getServiceRate() {
		return get("service_rate");
	}

	/**
	 * 分类（0：用户分润 1:平台分润3：订单分润）
	 */
	public void setIdentityType(java.lang.Integer identityType) {
		set("identity_type", identityType);
	}
	
	/**
	 * 分类（0：用户分润 1:平台分润3：订单分润）
	 */
	public java.lang.Integer getIdentityType() {
		return getInt("identity_type");
	}

	/**
	 * 交易前金额
	 */
	public void setBeforeAmount(java.math.BigDecimal beforeAmount) {
		set("before_amount", beforeAmount);
	}
	
	/**
	 * 交易前金额
	 */
	public java.math.BigDecimal getBeforeAmount() {
		return get("before_amount");
	}

	/**
	 * 交易后金额/最终利润(元)
	 */
	public void setAfterAmount(java.math.BigDecimal afterAmount) {
		set("after_amount", afterAmount);
	}
	
	/**
	 * 交易后金额/最终利润(元)
	 */
	public java.math.BigDecimal getAfterAmount() {
		return get("after_amount");
	}

	/**
	 * 入账方式（1：分账入账）
	 */
	public void setEnterAccountType(java.lang.Integer enterAccountType) {
		set("enter_account_type", enterAccountType);
	}
	
	/**
	 * 入账方式（1：分账入账）
	 */
	public java.lang.Integer getEnterAccountType() {
		return getInt("enter_account_type");
	}

	/**
	 * 分账状态（0：转账成功、1-分账到余额、2-审核中、3-微信预付款状态）
	 */
	public void setDisStatus(java.lang.Integer disStatus) {
		set("dis_status", disStatus);
	}
	
	/**
	 * 分账状态（0：转账成功、1-分账到余额、2-审核中、3-微信预付款状态）
	 */
	public java.lang.Integer getDisStatus() {
		return getInt("dis_status");
	}

	/**
	 * 描述
	 */
	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	/**
	 * 分账时间点(每日0时)
	 */
	public void setDisTime(java.util.Date disTime) {
		set("dis_time", disTime);
	}
	
	/**
	 * 分账时间点(每日0时)
	 */
	public java.util.Date getDisTime() {
		return get("dis_time");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 是否删除(0-false-未删除、1-true-已删除)
	 */
	public void setDelStatus(java.lang.Boolean delStatus) {
		set("del_status", delStatus);
	}
	
	/**
	 * 是否删除(0-false-未删除、1-true-已删除)
	 */
	public java.lang.Boolean getDelStatus() {
		return get("del_status");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 备注
	 */
	public void setDisNote(java.lang.String disNote) {
		set("dis_note", disNote);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getDisNote() {
		return getStr("dis_note");
	}

}
