package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsgBlueRecord<M extends BaseMsgBlueRecord<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 设备Id
	 */
	public void setDeviceId(java.lang.Long deviceId) {
		set("device_id", deviceId);
	}
	
	/**
	 * 设备Id
	 */
	public java.lang.Long getDeviceId() {
		return getLong("device_id");
	}

	/**
	 * 蓝牙状态
	 */
	public void setBlueStatus(java.lang.Integer blueStatus) {
		set("blue_status", blueStatus);
	}
	
	/**
	 * 蓝牙状态
	 */
	public java.lang.Integer getBlueStatus() {
		return getInt("blue_status");
	}

	/**
	 * 手机品牌
	 */
	public void setMobileBrand(java.lang.String mobileBrand) {
		set("mobile_brand", mobileBrand);
	}
	
	/**
	 * 手机品牌
	 */
	public java.lang.String getMobileBrand() {
		return getStr("mobile_brand");
	}

	/**
	 * 手机型号
	 */
	public void setMobileModel(java.lang.String mobileModel) {
		set("mobile_model", mobileModel);
	}
	
	/**
	 * 手机型号
	 */
	public java.lang.String getMobileModel() {
		return getStr("mobile_model");
	}

	/**
	 * 操作系统
	 */
	public void setMobileOs(java.lang.String mobileOs) {
		set("mobile_OS", mobileOs);
	}
	
	/**
	 * 操作系统
	 */
	public java.lang.String getMobileOs() {
		return getStr("mobile_OS");
	}

	/**
	 * 软件版本
	 */
	public void setSoftVersion(java.lang.String softVersion) {
		set("soft_version", softVersion);
	}
	
	/**
	 * 软件版本
	 */
	public java.lang.String getSoftVersion() {
		return getStr("soft_version");
	}

	/**
	 * 手机类型（ios、Android等）
	 */
	public void setMobileType(java.lang.String mobileType) {
		set("mobile_type", mobileType);
	}
	
	/**
	 * 手机类型（ios、Android等）
	 */
	public java.lang.String getMobileType() {
		return getStr("mobile_type");
	}

	/**
	 * Ip地址
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * Ip地址
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 信号接收时间
	 */
	public void setMsgTime(java.util.Date msgTime) {
		set("msg_time", msgTime);
	}
	
	/**
	 * 信号接收时间
	 */
	public java.util.Date getMsgTime() {
		return get("msg_time");
	}

	/**
	 * payload数据记录
	 */
	public void setRaw(java.lang.String raw) {
		set("raw", raw);
	}
	
	/**
	 * payload数据记录
	 */
	public java.lang.String getRaw() {
		return getStr("raw");
	}

}
