package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsAmountSituation<M extends BaseDdmsAmountSituation<M>> extends Model<M> implements IBean {

	/**
	 * 对账单表Id：账户变动表，用于记录账户变动情况
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 对账单表Id：账户变动表，用于记录账户变动情况
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 用户id
	 */
	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	/**
	 * 交易类型：0-分成入账、2-提现、3-提现返还、4-提现返还、5-余额调出、6-余额调出、7-红包策略删除返还、8-退款、9-余额充值、10-充值下级用户、11-受到上级充值、12-提取下级用户、13-受到上级提取、14-调入、15-调入、16-领取红包、17-投资人代偿红包、18-分账自动转账)
	 */
	public void setTradeType(java.lang.Integer tradeType) {
		set("trade_type", tradeType);
	}
	
	/**
	 * 交易类型：0-分成入账、2-提现、3-提现返还、4-提现返还、5-余额调出、6-余额调出、7-红包策略删除返还、8-退款、9-余额充值、10-充值下级用户、11-受到上级充值、12-提取下级用户、13-受到上级提取、14-调入、15-调入、16-领取红包、17-投资人代偿红包、18-分账自动转账)
	 */
	public java.lang.Integer getTradeType() {
		return getInt("trade_type");
	}

	/**
	 * 账户变动金额
	 */
	public void setChangeAmount(java.math.BigDecimal changeAmount) {
		set("change_amount", changeAmount);
	}
	
	/**
	 * 账户变动金额
	 */
	public java.math.BigDecimal getChangeAmount() {
		return get("change_amount");
	}

	/**
	 * 总账户变动之前余额
	 */
	public void setBeforeChangeAmount(java.math.BigDecimal beforeChangeAmount) {
		set("before_change_amount", beforeChangeAmount);
	}
	
	/**
	 * 总账户变动之前余额
	 */
	public java.math.BigDecimal getBeforeChangeAmount() {
		return get("before_change_amount");
	}

	/**
	 * 总账户变动之后余额
	 */
	public void setAfterChangeAmount(java.math.BigDecimal afterChangeAmount) {
		set("after_change_amount", afterChangeAmount);
	}
	
	/**
	 * 总账户变动之后余额
	 */
	public java.math.BigDecimal getAfterChangeAmount() {
		return get("after_change_amount");
	}

	/**
	 * 本次欠款
	 */
	public void setCurrentDebtAmount(java.math.BigDecimal currentDebtAmount) {
		set("current_debt_amount", currentDebtAmount);
	}
	
	/**
	 * 本次欠款
	 */
	public java.math.BigDecimal getCurrentDebtAmount() {
		return get("current_debt_amount");
	}

	/**
	 * 总欠款	
	 */
	public void setTotalDebtAmount(java.math.BigDecimal totalDebtAmount) {
		set("total_debt_amount", totalDebtAmount);
	}
	
	/**
	 * 总欠款	
	 */
	public java.math.BigDecimal getTotalDebtAmount() {
		return get("total_debt_amount");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 具体变动描述
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 具体变动描述
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
