package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDdmsRedPlanAdminRelation<M extends BaseDdmsRedPlanAdminRelation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 红包方案Id
	 */
	public void setRedId(java.lang.Long redId) {
		set("red_id", redId);
	}
	
	/**
	 * 红包方案Id
	 */
	public java.lang.Long getRedId() {
		return getLong("red_id");
	}

	/**
	 * 红包方案名称
	 */
	public void setRedName(java.lang.String redName) {
		set("red_name", redName);
	}
	
	/**
	 * 红包方案名称
	 */
	public java.lang.String getRedName() {
		return getStr("red_name");
	}

	/**
	 * 账户 id（登录账户）
	 */
	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 账户 id（登录账户）
	 */
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	/**
	 * 酒店管理员名称
	 */
	public void setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
	}
	
	/**
	 * 酒店管理员名称
	 */
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	/**
	 * 删除状态（1-true-未删除、0-false-已删除）
	 */
	public void setStatusDel(java.lang.Boolean statusDel) {
		set("status_del", statusDel);
	}
	
	/**
	 * 删除状态（1-true-未删除、0-false-已删除）
	 */
	public java.lang.Boolean getStatusDel() {
		return get("status_del");
	}

	/**
	 * 备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
