package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsDeviceProduct<M extends BaseDmsDeviceProduct<M>> extends Model<M> implements IBean {

	/**
	 * 设备与商品的绑定关系
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 设备与商品的绑定关系
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 设备 Id
	 */
	public void setDeviceId(java.math.BigInteger deviceId) {
		set("device_id", deviceId);
	}
	
	/**
	 * 设备 Id
	 */
	public java.math.BigInteger getDeviceId() {
		return get("device_id");
	}

	/**
	 * 设备编号
	 */
	public void setDeviceSn(java.lang.String deviceSn) {
		set("device_sn", deviceSn);
	}
	
	/**
	 * 设备编号
	 */
	public java.lang.String getDeviceSn() {
		return getStr("device_sn");
	}

	/**
	 * 设备格子（存在多个格子存放一套商品的可能）
	 */
	public void setDeviceCell(java.lang.String deviceCell) {
		set("device_cell", deviceCell);
	}
	
	/**
	 * 设备格子（存在多个格子存放一套商品的可能）
	 */
	public java.lang.String getDeviceCell() {
		return getStr("device_cell");
	}

	/**
	 * 商品Id
	 */
	public void setProductId(java.math.BigInteger productId) {
		set("product_id", productId);
	}
	
	/**
	 * 商品Id
	 */
	public java.math.BigInteger getProductId() {
		return get("product_id");
	}

	/**
	 * 商品售价（默认为商品方案的价格）
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 商品售价（默认为商品方案的价格）
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 是否缺货（1-不缺货，0-缺货）
	 */
	public void setStatusOutStock(java.lang.Boolean statusOutStock) {
		set("status_out_stock", statusOutStock);
	}
	
	/**
	 * 是否缺货（1-不缺货，0-缺货）
	 */
	public java.lang.Boolean getStatusOutStock() {
		return get("status_out_stock");
	}

	/**
	 * 是否锁定该商品（1-不锁定，0-锁定）（用户拍下(生成订单)时锁定，以防止多用户同时购买）
	 */
	public void setLockStock(java.lang.Boolean lockStock) {
		set("lock_stock", lockStock);
	}
	
	/**
	 * 是否锁定该商品（1-不锁定，0-锁定）（用户拍下(生成订单)时锁定，以防止多用户同时购买）
	 */
	public java.lang.Boolean getLockStock() {
		return get("lock_stock");
	}

}
