package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUmsTask<M extends BaseUmsTask<M>> extends Model<M> implements IBean {

	/**
	 * 任务表ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 任务表ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 任务的名称
	 */
	public void setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
	}
	
	/**
	 * 任务的名称
	 */
	public java.lang.String getTaskName() {
		return getStr("task_name");
	}

	/**
	 * 1-换货2-巡检3-换电池4-更换程序
	 */
	public void setTaskType(java.lang.Integer taskType) {
		set("task_type", taskType);
	}
	
	/**
	 * 1-换货2-巡检3-换电池4-更换程序
	 */
	public java.lang.Integer getTaskType() {
		return getInt("task_type");
	}

	/**
	 * 场所的ID
	 */
	public void setPlaceId(java.lang.Integer placeId) {
		set("place_id", placeId);
	}
	
	/**
	 * 场所的ID
	 */
	public java.lang.Integer getPlaceId() {
		return getInt("place_id");
	}

	/**
	 * 场所的名称
	 */
	public void setPlaceName(java.lang.String placeName) {
		set("place_name", placeName);
	}
	
	/**
	 * 场所的名称
	 */
	public java.lang.String getPlaceName() {
		return getStr("place_name");
	}

	/**
	 * 商品的id
	 */
	public void setCommodityId(java.lang.Integer commodityId) {
		set("commodity_id", commodityId);
	}
	
	/**
	 * 商品的id
	 */
	public java.lang.Integer getCommodityId() {
		return getInt("commodity_id");
	}

	/**
	 * 商品的名称
	 */
	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	/**
	 * 商品的名称
	 */
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	/**
	 * 创建的时间
	 */
	public void setCreationTime(java.util.Date creationTime) {
		set("creation_time", creationTime);
	}
	
	/**
	 * 创建的时间
	 */
	public java.util.Date getCreationTime() {
		return get("creation_time");
	}

	/**
	 * 1-进行中2-已完成
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 1-进行中2-已完成
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
