package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHmsHotelAdmin<M extends BaseHmsHotelAdmin<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 酒店 id
	 */
	public void setHotelId(java.lang.Long hotelId) {
		set("hotel_id", hotelId);
	}
	
	/**
	 * 酒店 id
	 */
	public java.lang.Long getHotelId() {
		return getLong("hotel_id");
	}

	/**
	 * 酒店名称
	 */
	public void setHotelName(java.lang.String hotelName) {
		set("hotel_name", hotelName);
	}
	
	/**
	 * 酒店名称
	 */
	public java.lang.String getHotelName() {
		return getStr("hotel_name");
	}

	/**
	 * 账户 id（登录账户）
	 */
	public void setAdminId(java.lang.Long adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 账户 id（登录账户）
	 */
	public java.lang.Long getAdminId() {
		return getLong("admin_id");
	}

	/**
	 * 酒店管理员名称
	 */
	public void setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
	}
	
	/**
	 * 酒店管理员名称
	 */
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	/**
	 * 绑定关系枚举类BindType：酒店与人员的绑定关系：2-推广关系、3-酒店管理（场所）、4-酒店补货
	 */
	public void setBindType(java.lang.Integer bindType) {
		set("bind_type", bindType);
	}
	
	/**
	 * 绑定关系枚举类BindType：酒店与人员的绑定关系：2-推广关系、3-酒店管理（场所）、4-酒店补货
	 */
	public java.lang.Integer getBindType() {
		return getInt("bind_type");
	}

	/**
	 * 是否启用该关系（0-false-不启用、1-true-启用）
	 */
	public void setIsEnable(java.lang.Boolean isEnable) {
		set("is_enable", isEnable);
	}
	
	/**
	 * 是否启用该关系（0-false-不启用、1-true-启用）
	 */
	public java.lang.Boolean getIsEnable() {
		return get("is_enable");
	}

	/**
	 * 备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

	/**
	 * 分成比例（x%）
	 */
	public void setShareRatio(java.math.BigDecimal shareRatio) {
		set("share_ratio", shareRatio);
	}
	
	/**
	 * 分成比例（x%）
	 */
	public java.math.BigDecimal getShareRatio() {
		return get("share_ratio");
	}

	/**
	 * 每次给这个用户分成的时候，需要扣除的手续费
	 */
	public void setServiceRate(java.math.BigDecimal serviceRate) {
		set("service_rate", serviceRate);
	}
	
	/**
	 * 每次给这个用户分成的时候，需要扣除的手续费
	 */
	public java.math.BigDecimal getServiceRate() {
		return get("service_rate");
	}

}
