package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderHotelTest<M extends BaseOrderHotelTest<M>> extends Model<M> implements IBean {

	/**
	 * 酒店场所表格ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 酒店场所表格ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 详细地址
	 */
	public void setDetailedAddress(java.lang.String detailedAddress) {
		set("detailed_address", detailedAddress);
	}
	
	/**
	 * 详细地址
	 */
	public java.lang.String getDetailedAddress() {
		return getStr("detailed_address");
	}

	/**
	 * 场所名称
	 */
	public void setPlaceName(java.lang.String placeName) {
		set("place_name", placeName);
	}
	
	/**
	 * 场所名称
	 */
	public java.lang.String getPlaceName() {
		return getStr("place_name");
	}

	/**
	 * 激活设备数量
	 */
	public void setActivateDevice(java.lang.Integer activateDevice) {
		set("activate_device", activateDevice);
	}
	
	/**
	 * 激活设备数量
	 */
	public java.lang.Integer getActivateDevice() {
		return getInt("activate_device");
	}

	/**
	 * 合伙人
	 */
	public void setPartnerUser(java.lang.String partnerUser) {
		set("partner_user", partnerUser);
	}
	
	/**
	 * 合伙人
	 */
	public java.lang.String getPartnerUser() {
		return getStr("partner_user");
	}

	/**
	 * db
	 */
	public void setUserBd(java.lang.String userBd) {
		set("user_bd", userBd);
	}
	
	/**
	 * db
	 */
	public java.lang.String getUserBd() {
		return getStr("user_bd");
	}

}
