package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOmsOrderItem<M extends BaseOmsOrderItem<M>> extends Model<M> implements IBean {

	/**
	 * 订单商品信息Id
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 订单商品信息Id
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 订单id
	 */
	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}
	
	/**
	 * 订单id
	 */
	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	/**
	 * 订单编号
	 */
	public void setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
	}
	
	/**
	 * 订单编号
	 */
	public java.lang.String getOrderSn() {
		return getStr("order_sn");
	}

	/**
	 * 货到/格子号
	 */
	public void setCellNo(java.lang.String cellNo) {
		set("cell_no", cellNo);
	}
	
	/**
	 * 货到/格子号
	 */
	public java.lang.String getCellNo() {
		return getStr("cell_no");
	}

	/**
	 * 商品id
	 */
	public void setProductId(java.lang.Long productId) {
		set("product_id", productId);
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	/**
	 * 商品图片
	 */
	public void setProductPic(java.lang.String productPic) {
		set("product_pic", productPic);
	}
	
	/**
	 * 商品图片
	 */
	public java.lang.String getProductPic() {
		return getStr("product_pic");
	}

	/**
	 * 商品名称
	 */
	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	/**
	 * 商品品牌
	 */
	public void setProductBrand(java.lang.String productBrand) {
		set("product_brand", productBrand);
	}
	
	/**
	 * 商品品牌
	 */
	public java.lang.String getProductBrand() {
		return getStr("product_brand");
	}

	/**
	 * 商品条码（商品编号）
	 */
	public void setProductSn(java.lang.String productSn) {
		set("product_sn", productSn);
	}
	
	/**
	 * 商品条码（商品编号）
	 */
	public java.lang.String getProductSn() {
		return getStr("product_sn");
	}

	/**
	 * 销售价格
	 */
	public void setProductPrice(java.math.BigDecimal productPrice) {
		set("product_price", productPrice);
	}
	
	/**
	 * 销售价格
	 */
	public java.math.BigDecimal getProductPrice() {
		return get("product_price");
	}

	/**
	 * 购买数量
	 */
	public void setProductQuantity(java.lang.Integer productQuantity) {
		set("product_quantity", productQuantity);
	}
	
	/**
	 * 购买数量
	 */
	public java.lang.Integer getProductQuantity() {
		return getInt("product_quantity");
	}

	/**
	 * 该商品经过优惠后的实付金额
	 */
	public void setRealAmount(java.math.BigDecimal realAmount) {
		set("real_amount", realAmount);
	}
	
	/**
	 * 该商品经过优惠后的实付金额
	 */
	public java.math.BigDecimal getRealAmount() {
		return get("real_amount");
	}

	/**
	 * 商品sku编号
	 */
	public void setProductSkuId(java.lang.Long productSkuId) {
		set("product_sku_id", productSkuId);
	}
	
	/**
	 * 商品sku编号
	 */
	public java.lang.Long getProductSkuId() {
		return getLong("product_sku_id");
	}

	/**
	 * 商品sku条码
	 */
	public void setProductSkuCode(java.lang.String productSkuCode) {
		set("product_sku_code", productSkuCode);
	}
	
	/**
	 * 商品sku条码
	 */
	public java.lang.String getProductSkuCode() {
		return getStr("product_sku_code");
	}

	/**
	 * 商品分类id
	 */
	public void setProductCategoryId(java.lang.Long productCategoryId) {
		set("product_category_id", productCategoryId);
	}
	
	/**
	 * 商品分类id
	 */
	public java.lang.Long getProductCategoryId() {
		return getLong("product_category_id");
	}

	/**
	 * 商品的销售属性（SKU遗留问题，暂不使用）
	 */
	public void setSp1(java.lang.String sp1) {
		set("sp1", sp1);
	}
	
	/**
	 * 商品的销售属性（SKU遗留问题，暂不使用）
	 */
	public java.lang.String getSp1() {
		return getStr("sp1");
	}

	/**
	 * 暂不使用
	 */
	public void setSp2(java.lang.String sp2) {
		set("sp2", sp2);
	}
	
	/**
	 * 暂不使用
	 */
	public java.lang.String getSp2() {
		return getStr("sp2");
	}

	/**
	 * 暂不使用
	 */
	public void setSp3(java.lang.String sp3) {
		set("sp3", sp3);
	}
	
	/**
	 * 暂不使用
	 */
	public java.lang.String getSp3() {
		return getStr("sp3");
	}

	/**
	 * 商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
	 */
	public void setProductAttr(java.lang.String productAttr) {
		set("product_attr", productAttr);
	}
	
	/**
	 * 商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
	 */
	public java.lang.String getProductAttr() {
		return getStr("product_attr");
	}

	/**
	 * 商品促销名称
	 */
	public void setPromotionName(java.lang.String promotionName) {
		set("promotion_name", promotionName);
	}
	
	/**
	 * 商品促销名称
	 */
	public java.lang.String getPromotionName() {
		return getStr("promotion_name");
	}

	/**
	 * 商品促销分解金额
	 */
	public void setPromotionAmount(java.math.BigDecimal promotionAmount) {
		set("promotion_amount", promotionAmount);
	}
	
	/**
	 * 商品促销分解金额
	 */
	public java.math.BigDecimal getPromotionAmount() {
		return get("promotion_amount");
	}

	/**
	 * 优惠券优惠分解金额
	 */
	public void setCouponAmount(java.math.BigDecimal couponAmount) {
		set("coupon_amount", couponAmount);
	}
	
	/**
	 * 优惠券优惠分解金额
	 */
	public java.math.BigDecimal getCouponAmount() {
		return get("coupon_amount");
	}

	/**
	 * 积分优惠分解金额
	 */
	public void setIntegrationAmount(java.math.BigDecimal integrationAmount) {
		set("integration_amount", integrationAmount);
	}
	
	/**
	 * 积分优惠分解金额
	 */
	public java.math.BigDecimal getIntegrationAmount() {
		return get("integration_amount");
	}

	/**
	 * 商品赠送积分
	 */
	public void setGiftIntegration(java.lang.Integer giftIntegration) {
		set("gift_integration", giftIntegration);
	}
	
	/**
	 * 商品赠送积分
	 */
	public java.lang.Integer getGiftIntegration() {
		return getInt("gift_integration");
	}

	/**
	 * 商品赠送成长值
	 */
	public void setGiftGrowth(java.lang.Integer giftGrowth) {
		set("gift_growth", giftGrowth);
	}
	
	/**
	 * 商品赠送成长值
	 */
	public java.lang.Integer getGiftGrowth() {
		return getInt("gift_growth");
	}

}
