package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmsReplenishmentRecord<M extends BaseDmsReplenishmentRecord<M>> extends Model<M> implements IBean {

	/**
	 * 补货记录表的主键Id
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 补货记录表的主键Id
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 补货员Id
	 */
	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 补货员Id
	 */
	public java.lang.Integer getAdminId() {
		return getInt("admin_id");
	}

	/**
	 * 补货类型1-补货2-设置缺货3-更换商品4-一键测试5-快捷上货
	 */
	public void setReplenishType(java.lang.Long replenishType) {
		set("replenish_type", replenishType);
	}
	
	/**
	 * 补货类型1-补货2-设置缺货3-更换商品4-一键测试5-快捷上货
	 */
	public java.lang.Long getReplenishType() {
		return getLong("replenish_type");
	}

	/**
	 * 场所Id
	 */
	public void setHotelId(java.lang.Integer hotelId) {
		set("hotel_id", hotelId);
	}
	
	/**
	 * 场所Id
	 */
	public java.lang.Integer getHotelId() {
		return getInt("hotel_id");
	}

	/**
	 * 设备编号
	 */
	public void setDeviceSn(java.lang.String deviceSn) {
		set("device_sn", deviceSn);
	}
	
	/**
	 * 设备编号
	 */
	public java.lang.String getDeviceSn() {
		return getStr("device_sn");
	}

	/**
	 * 补货格子号
	 */
	public void setCellNo(java.lang.String cellNo) {
		set("cell_no", cellNo);
	}
	
	/**
	 * 补货格子号
	 */
	public java.lang.String getCellNo() {
		return getStr("cell_no");
	}

	/**
	 * 房间号
	 */
	public void setRoomNo(java.lang.String roomNo) {
		set("room_no", roomNo);
	}
	
	/**
	 * 房间号
	 */
	public java.lang.String getRoomNo() {
		return getStr("room_no");
	}

	/**
	 * 操作时间
	 */
	public void setOpTime(java.util.Date opTime) {
		set("op_time", opTime);
	}
	
	/**
	 * 操作时间
	 */
	public java.util.Date getOpTime() {
		return get("op_time");
	}

}
