package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUmsResource<M extends BaseUmsResource<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 资源名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 资源名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 资源URL
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 资源URL
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 资源分类ID
	 */
	public void setCategoryId(java.lang.Long categoryId) {
		set("category_id", categoryId);
	}
	
	/**
	 * 资源分类ID
	 */
	public java.lang.Long getCategoryId() {
		return getLong("category_id");
	}

}
