package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSmsHomeAdvertise<M extends BaseSmsHomeAdvertise<M>> extends Model<M> implements IBean {

	/**
	 * 首页轮播广告表 Id
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 首页轮播广告表 Id
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 轮播位置：0->PC首页轮播；1->app首页轮播；2->小程序首页轮播
	 */
	public void setType(java.lang.Long type) {
		set("type", type);
	}
	
	/**
	 * 轮播位置：0->PC首页轮播；1->app首页轮播；2->小程序首页轮播
	 */
	public java.lang.Long getType() {
		return getLong("type");
	}

	/**
	 * 广告拥有者：1-系统；2-推广人；3-酒店管理；4-合伙人
	 */
	public void setUseType(java.lang.Integer useType) {
		set("use_type", useType);
	}
	
	/**
	 * 广告拥有者：1-系统；2-推广人；3-酒店管理；4-合伙人
	 */
	public java.lang.Integer getUseType() {
		return getInt("use_type");
	}

	/**
	 * 广告图片 OSS 图片地址
	 */
	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}
	
	/**
	 * 广告图片 OSS 图片地址
	 */
	public java.lang.String getPic() {
		return getStr("pic");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	/**
	 * 上下线状态：0->下线；1->上线
	 */
	public void setStatus(java.lang.Long status) {
		set("status", status);
	}
	
	/**
	 * 上下线状态：0->下线；1->上线
	 */
	public java.lang.Long getStatus() {
		return getLong("status");
	}

	/**
	 * 点击数
	 */
	public void setClickCount(java.lang.Integer clickCount) {
		set("click_count", clickCount);
	}
	
	/**
	 * 点击数
	 */
	public java.lang.Integer getClickCount() {
		return getInt("click_count");
	}

	/**
	 * 下单数
	 */
	public void setOrderCount(java.lang.Integer orderCount) {
		set("order_count", orderCount);
	}
	
	/**
	 * 下单数
	 */
	public java.lang.Integer getOrderCount() {
		return getInt("order_count");
	}

	/**
	 * 链接地址
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 链接地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
