package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrdersScanTest<M extends BaseOrdersScanTest<M>> extends Model<M> implements IBean {

	/**
	 * 扫码表格ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 扫码表格ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 设备ID
	 */
	public void setDevId(java.lang.String devId) {
		set("dev_id", devId);
	}
	
	/**
	 * 设备ID
	 */
	public java.lang.String getDevId() {
		return getStr("dev_id");
	}

	/**
	 * 场所名称
	 */
	public void setPlaceName(java.lang.String placeName) {
		set("place_name", placeName);
	}
	
	/**
	 * 场所名称
	 */
	public java.lang.String getPlaceName() {
		return getStr("place_name");
	}

	/**
	 * 房间号
	 */
	public void setRoomNumber(java.lang.String roomNumber) {
		set("room_number", roomNumber);
	}
	
	/**
	 * 房间号
	 */
	public java.lang.String getRoomNumber() {
		return getStr("room_number");
	}

	/**
	 * 合伙人名称
	 */
	public void setPartnerUser(java.lang.String partnerUser) {
		set("partner_user", partnerUser);
	}
	
	/**
	 * 合伙人名称
	 */
	public java.lang.String getPartnerUser() {
		return getStr("partner_user");
	}

	/**
	 * 扫码的时间
	 */
	public void setSweepTimeCode(java.lang.String sweepTimeCode) {
		set("sweep_time_code", sweepTimeCode);
	}
	
	/**
	 * 扫码的时间
	 */
	public java.lang.String getSweepTimeCode() {
		return getStr("sweep_time_code");
	}

	/**
	 * 扫码的ip地址
	 */
	public void setCodeIp(java.lang.String codeIp) {
		set("code_ip", codeIp);
	}
	
	/**
	 * 扫码的ip地址
	 */
	public java.lang.String getCodeIp() {
		return getStr("code_ip");
	}

}
