package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanProduct<M extends BasePlanProduct<M>> extends Model<M> implements IBean {

	/**
	 * 商品方案表的Id
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 商品方案表的Id
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 方案名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 方案名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 分成类型，枚举类DivideModeType（1-营业额，2-利润，3-商品的分成）
	 */
	public void setDivideMode(java.lang.Long divideMode) {
		set("divide_mode", divideMode);
	}
	
	/**
	 * 分成类型，枚举类DivideModeType（1-营业额，2-利润，3-商品的分成）
	 */
	public java.lang.Long getDivideMode() {
		return getLong("divide_mode");
	}

	/**
	 * 适配机型编号
	 */
	public void setDevModeSn(java.lang.String devModeSn) {
		set("dev_mode_sn", devModeSn);
	}
	
	/**
	 * 适配机型编号
	 */
	public java.lang.String getDevModeSn() {
		return getStr("dev_mode_sn");
	}

	/**
	 * 方案详情，json格式（cell:格子号, productId:商品Id, price:价钱,productName:商品名称）
	 */
	public void setDetails(java.lang.String details) {
		set("details", details);
	}
	
	/**
	 * 方案详情，json格式（cell:格子号, productId:商品Id, price:价钱,productName:商品名称）
	 */
	public java.lang.String getDetails() {
		return getStr("details");
	}

	/**
	 * 状态（0-删除，1-未删除）
	 */
	public void setStatusDel(java.lang.Integer statusDel) {
		set("status_del", statusDel);
	}
	
	/**
	 * 状态（0-删除，1-未删除）
	 */
	public java.lang.Integer getStatusDel() {
		return getInt("status_del");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 备注
	 */
	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
