package com.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ddms_admin_amount", "id", DdmsAdminAmount.class);
		arp.addMapping("ddms_amount_situation", "id", DdmsAmountSituation.class);
		arp.addMapping("ddms_distribution_plan", "id", DdmsDistributionPlan.class);
		arp.addMapping("ddms_hotel_dist_relation", "id", DdmsHotelDistRelation.class);
		arp.addMapping("ddms_msg_daily_dist", "id", DdmsMsgDailyDist.class);
		arp.addMapping("ddms_order_dist_record", "id", DdmsOrderDistRecord.class);
		arp.addMapping("ddms_profit_record", "id", DdmsProfitRecord.class);
		arp.addMapping("ddms_red_plan", "red_id", DdmsRedPlan.class);
		arp.addMapping("ddms_red_plan_admin_relation", "id", DdmsRedPlanAdminRelation.class);
		arp.addMapping("ddms_red_plan_hotel_relation", "id", DdmsRedPlanHotelRelation.class);
		arp.addMapping("ddms_withdraw_conf", "id", DdmsWithdrawConf.class);
		arp.addMapping("ddms_withdraw_record", "id", DdmsWithdrawRecord.class);
		arp.addMapping("dms_device", "id", DmsDevice.class);
		arp.addMapping("dms_device_admin", "id", DmsDeviceAdmin.class);
		arp.addMapping("dms_device_maintain", "id", DmsDeviceMaintain.class);
		arp.addMapping("dms_device_mode", "id", DmsDeviceMode.class);
		arp.addMapping("dms_device_product", "id", DmsDeviceProduct.class);
		arp.addMapping("dms_device_product_plan", "id", DmsDeviceProductPlan.class);
		arp.addMapping("dms_device_qrcode_record", "id", DmsDeviceQrcodeRecord.class);
		arp.addMapping("dms_device_status", "device_id", DmsDeviceStatus.class);
		arp.addMapping("dms_replenishment_record", "id", DmsReplenishmentRecord.class);
		arp.addMapping("hms_hotel", "id", HmsHotel.class);
		arp.addMapping("hms_hotel_admin", "id", HmsHotelAdmin.class);
		arp.addMapping("hms_hotel_device", "id", HmsHotelDevice.class);
		arp.addMapping("hms_hotel_type", "id", HmsHotelType.class);
		arp.addMapping("msg_blue_record", "id", MsgBlueRecord.class);
		arp.addMapping("oms_order", "id", OmsOrder.class);
		arp.addMapping("oms_order_item", "id", OmsOrderItem.class);
		arp.addMapping("oms_order_setting", "id", OmsOrderSetting.class);
		arp.addMapping("order_hotel_test", "id", OrderHotelTest.class);
		arp.addMapping("order_hotel_test_two", "id", OrderHotelTestTwo.class);
		arp.addMapping("order_test", "id", OrderTest.class);
		arp.addMapping("orders_refund_test", "id", OrdersRefundTest.class);
		arp.addMapping("orders_scan_test", "id", OrdersScanTest.class);
		arp.addMapping("plan_product", "id", PlanProduct.class);
		arp.addMapping("plan_product_admin", "id", PlanProductAdmin.class);
		arp.addMapping("plan_product_hotel", "id", PlanProductHotel.class);
		arp.addMapping("pms_album", "id", PmsAlbum.class);
		arp.addMapping("pms_album_pic", "id", PmsAlbumPic.class);
		arp.addMapping("pms_brand", "id", PmsBrand.class);
		arp.addMapping("pms_picture", "id", PmsPicture.class);
		arp.addMapping("pms_product", "id", PmsProduct.class);
		arp.addMapping("pms_product_admin_relation", "id", PmsProductAdminRelation.class);
		arp.addMapping("pms_product_album_relation", "id", PmsProductAlbumRelation.class);
		arp.addMapping("pms_product_category", "id", PmsProductCategory.class);
		arp.addMapping("pms_product_picture_relation", "id", PmsProductPictureRelation.class);
		arp.addMapping("pms_product_plan", "id", PmsProductPlan.class);
		arp.addMapping("sms_home_advertise", "id", SmsHomeAdvertise.class);
		arp.addMapping("sms_hotel_adverties_relation", "id", SmsHotelAdvertiesRelation.class);
		arp.addMapping("ums_admin", "id", UmsAdmin.class);
		arp.addMapping("ums_admin_login_log", "id", UmsAdminLoginLog.class);
		arp.addMapping("ums_admin_pay", "id", UmsAdminPay.class);
		arp.addMapping("ums_admin_permission_relation", "id", UmsAdminPermissionRelation.class);
		arp.addMapping("ums_admin_role_relation", "id", UmsAdminRoleRelation.class);
		arp.addMapping("ums_member", "id", UmsMember.class);
		arp.addMapping("ums_menu", "id", UmsMenu.class);
		arp.addMapping("ums_problem_feedback", "id", UmsProblemFeedback.class);
		arp.addMapping("ums_resource", "id", UmsResource.class);
		arp.addMapping("ums_resource_category", "id", UmsResourceCategory.class);
		arp.addMapping("ums_role", "id", UmsRole.class);
		arp.addMapping("ums_role_menu_relation", "id", UmsRoleMenuRelation.class);
		arp.addMapping("ums_role_resource_relation", "id", UmsRoleResourceRelation.class);
		arp.addMapping("ums_task", "id", UmsTask.class);
	}
}

