package com.model;

import com.model.base.BaseDdmsOrderDistRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsOrderDistRecord extends BaseDdmsOrderDistRecord<DdmsOrderDistRecord> {
	
}
