package com.model;

import com.model.base.BaseDdmsAdminAmount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsAdminAmount extends BaseDdmsAdminAmount<DdmsAdminAmount> {
	
}
