package com.model;

import com.model.base.BaseDdmsWithdrawConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsWithdrawConf extends BaseDdmsWithdrawConf<DdmsWithdrawConf> {
	
}
