package com.model;

import com.model.base.BaseDdmsRedPlanHotelRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsRedPlanHotelRelation extends BaseDdmsRedPlanHotelRelation<DdmsRedPlanHotelRelation> {
	
}
