package com.model;

import com.model.base.BaseDdmsHotelDistRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsHotelDistRelation extends BaseDdmsHotelDistRelation<DdmsHotelDistRelation> {
	
}
