package com.model;

import com.model.base.BaseDdmsMsgDailyDist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsMsgDailyDist extends BaseDdmsMsgDailyDist<DdmsMsgDailyDist> {
	
}
