package com.model;

import com.model.base.BaseDdmsProfitRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsProfitRecord extends BaseDdmsProfitRecord<DdmsProfitRecord> {
	
}
