package com.model;

import com.model.base.BaseDdmsWithdrawRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsWithdrawRecord extends BaseDdmsWithdrawRecord<DdmsWithdrawRecord> {
	
}
