package com.model;

import com.model.base.BaseDdmsDistributionPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsDistributionPlan extends BaseDdmsDistributionPlan<DdmsDistributionPlan> {
	
}
