package com.model;

import com.model.base.BaseDdmsRedPlanAdminRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsRedPlanAdminRelation extends BaseDdmsRedPlanAdminRelation<DdmsRedPlanAdminRelation> {
	
}
