package com.model;

import com.model.base.BaseDdmsAmountSituation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DdmsAmountSituation extends BaseDdmsAmountSituation<DdmsAmountSituation> {
	
}
