package com.model;

import com.model.base.BaseDmsDeviceProductPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmsDeviceProductPlan extends BaseDmsDeviceProductPlan<DmsDeviceProductPlan> {
	
}
