package com.model;

import com.model.base.BaseDmsDeviceProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmsDeviceProduct extends BaseDmsDeviceProduct<DmsDeviceProduct> {
	
}
