package com.model;

import com.model.base.BaseDmsDeviceStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmsDeviceStatus extends BaseDmsDeviceStatus<DmsDeviceStatus> {
	
}
