package com.model;

import com.model.base.BaseDmsDeviceQrcodeRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmsDeviceQrcodeRecord extends BaseDmsDeviceQrcodeRecord<DmsDeviceQrcodeRecord> {
	
}
