package com.model;

import com.model.base.BaseDmsDeviceAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmsDeviceAdmin extends BaseDmsDeviceAdmin<DmsDeviceAdmin> {
	
}
