package com.model;

import com.model.base.BaseDmsDeviceMaintain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmsDeviceMaintain extends BaseDmsDeviceMaintain<DmsDeviceMaintain> {
	
}
