package com.model;

import com.model.base.BaseDmsReplenishmentRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmsReplenishmentRecord extends BaseDmsReplenishmentRecord<DmsReplenishmentRecord> {
	
}
