package com.model;

import com.model.base.BaseHmsHotelDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HmsHotelDevice extends BaseHmsHotelDevice<HmsHotelDevice> {
	
}
