package com.model;

import com.model.base.BaseOmsOrderSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmsOrderSetting extends BaseOmsOrderSetting<OmsOrderSetting> {
	
}
