package com.model;

import com.model.base.BaseOrderHotelTestTwo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderHotelTestTwo extends BaseOrderHotelTestTwo<OrderHotelTestTwo> {
	
}
