package com.model;

import com.model.base.BaseOrderHotelTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderHotelTest extends BaseOrderHotelTest<OrderHotelTest> {
	
}
