package com.model;

import com.model.base.BaseOrdersScanTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrdersScanTest extends BaseOrdersScanTest<OrdersScanTest> {
	
}
