package com.model;

import com.model.base.BaseOrdersRefundTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrdersRefundTest extends BaseOrdersRefundTest<OrdersRefundTest> {
	
}
