package com.model;

import com.model.base.BasePlanProductHotel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanProductHotel extends BasePlanProductHotel<PlanProductHotel> {
	
}
