package com.model;

import com.model.base.BasePlanProductAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanProductAdmin extends BasePlanProductAdmin<PlanProductAdmin> {
	
}
