package com.model;

import com.model.base.BasePmsProductAlbumRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmsProductAlbumRelation extends BasePmsProductAlbumRelation<PmsProductAlbumRelation> {
	
}
