package com.model;

import com.model.base.BasePmsProductPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmsProductPlan extends BasePmsProductPlan<PmsProductPlan> {
	
}
