package com.model;

import com.model.base.BasePmsProductAdminRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmsProductAdminRelation extends BasePmsProductAdminRelation<PmsProductAdminRelation> {
	
}
