package com.model;

import com.model.base.BasePmsProductPictureRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmsProductPictureRelation extends BasePmsProductPictureRelation<PmsProductPictureRelation> {
	
}
