package com.model;

import com.model.base.BasePmsProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmsProductCategory extends BasePmsProductCategory<PmsProductCategory> {
	
}
