package com.model;

import com.model.base.BaseSmsHotelAdvertiesRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsHotelAdvertiesRelation extends BaseSmsHotelAdvertiesRelation<SmsHotelAdvertiesRelation> {
	
}
