package com.model;

import com.model.base.BaseUmsAdminLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UmsAdminLoginLog extends BaseUmsAdminLoginLog<UmsAdminLoginLog> {
	
}
