package com.model;

import com.model.base.BaseUmsAdminRoleRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UmsAdminRoleRelation extends BaseUmsAdminRoleRelation<UmsAdminRoleRelation> {
	
}
