package com.model;

import com.model.base.BaseUmsAdminPermissionRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UmsAdminPermissionRelation extends BaseUmsAdminPermissionRelation<UmsAdminPermissionRelation> {
	
}
