package com.model;

import com.model.base.BaseUmsProblemFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UmsProblemFeedback extends BaseUmsProblemFeedback<UmsProblemFeedback> {
	
}
