package com.model;

import com.model.base.BaseUmsRoleMenuRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UmsRoleMenuRelation extends BaseUmsRoleMenuRelation<UmsRoleMenuRelation> {
	
}
