package com.model;

import com.model.base.BaseUmsResourceCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UmsResourceCategory extends BaseUmsResourceCategory<UmsResourceCategory> {
	
}
