package com.model;

import com.model.base.BaseUmsRoleResourceRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UmsRoleResourceRelation extends BaseUmsRoleResourceRelation<UmsRoleResourceRelation> {
	
}
